### PR TITLE
Fix #2750

### LINKED ISSUE #2750: SPIFFSFS class should not shadow methods in FS class
Please see https://github.com/espressif/esp-idf/issues/3427 for code samples, platform details and discussion. To summarize:

The FS class is not designed to be subclassed insofar as none of its methods are virtual. Re-implementing those methods in SPIFFSFS does not override them, it hides them, so instances of SPIFFSFS can not be passed as references or pointers to the FS class. If they are, the FS methods will be called instead and will not work reliably for a SPIFFS filing system (the existing unit tests are all positive - they test that things work when the files are as they are supposed to be, they don't test negative situations such as files not actually existing).

Instead, an instance of a SPIFFSFS class (such as the instance called _SPIFFS_) should inject a SPIFFS-specific implementation class into the superclass.

### PR DESCRIPTION
**Pull request by judge2005**
This is a fix for https://github.com/espressif/arduino-esp32/issues/2750

### CODE REVIEW

File: libraries/SPIFFS/src/SPIFFS.cpp [hunk 1]
```diff
@@ -1,32 +1,26 @@
...
 using namespace fs;
 
-SPIFFSFS::SPIFFSFS(FSImplPtr impl)
-    : FS(impl)
-{}
+SPIFFSImpl::SPIFFSImpl()
+{
+}
+
+bool SPIFFSImpl::exists(const char* path) {
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.cpp]: please use a new line before the curly braces. I see this a few more times below :)

File: libraries/SPIFFS/src/SPIFFS.cpp [hunk 2]
```diff
@@ -1,32 +1,26 @@
-// Copyright 2015-2016 Espressif Systems (Shanghai) PTE LTD
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.cpp]: Do not remove the headers!

File: libraries/SPIFFS/src/SPIFFS.h [hunk 3]
```diff
@@ -1,39 +1,33 @@
-// Copyright 2015-2016 Espressif Systems (Shanghai) PTE LTD
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.h]: Do not remove the headers!

File: libraries/SPIFFS/src/SPIFFS.h [hunk 4]
```diff
@@ -1,39 +1,33 @@
...
+#include "FSImpl.h"
+#include "vfs_api.h"
 
 namespace fs
 {
 
+class SPIFFSImpl : public VFSImpl
+{
+public:
+	SPIFFSImpl();
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.h]: too much space?

**Comment by me-no-dev** [comment]
Left a few styling notes. Not sure why you deleted the company headers?

**Comment by judge2005** [comment]
> Left a few styling notes. Not sure why you deleted the company headers?
I implemented these changes in separate files and then overwrote the originals. Anyway - I've added them back...

**Comment by judge2005** [comment]
I merged all of the recent changes into my fork before committing fixes for this. Not sure what effect that will have on attempts by you to merge this specific change to SPIFFS.

File: libraries/SPIFFS/src/SPIFFS.h [hunk 5]
```diff
@@ -14,26 +14,37 @@
 #ifndef _SPIFFS_H_
 #define _SPIFFS_H_
 
+#pragma once
+
 #include "FS.h"
+#include "FSImpl.h"
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.h]: these two includes should not be in the header, but in the CPP file instead. Nothing in the header depends on them :)

File: libraries/SPIFFS/src/SPIFFS.h [hunk 6]
```diff
@@ -14,26 +14,37 @@
 #ifndef _SPIFFS_H_
 #define _SPIFFS_H_
 
+#pragma once
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.h]: this is redundant with the above. keep one or the other :)

File: libraries/SPIFFS/src/SPIFFS.h (hunk 5 above)
Comment (judge2005) [reply libraries/SPIFFS/src/SPIFFS.h]: The header **does** depend on them, but they are also included via vfs_api.h, so at most they are redundant. For the same reason they don't need to be included in the .cpp file (because they are included via vfs_api.h which is included via SPIFFS.h).

Whatever, I have removed them from SPIFFS.h, but I haven't added them to SPIFFS.cpp.

File: libraries/SPIFFS/src/SPIFFS.h [hunk 7]
```diff
@@ -14,26 +14,33 @@
 #ifndef _SPIFFS_H_
 #define _SPIFFS_H_
 
-#include "FS.h"
+#include "vfs_api.h"
```
Comment (me-no-dev) [inline libraries/SPIFFS/src/SPIFFS.h]: FS should be included. vfs_api is a private header.

Comment (judge2005) [reply libraries/SPIFFS/src/SPIFFS.h]: 18 hours ago, you asked me to remove FS.h and FSImpl.h, now you are asking me to add FS.h back in.

If I remove vfs_api.h I will also have to add  FSImpl.h back because SPIFFSImpl is declared in SPIFFS.h.

Comment (me-no-dev) [reply libraries/SPIFFS/src/SPIFFS.h]: No, I asked about `#include "FSImpl.h"` and `#include "vfs_api.h"`.
FS.h is the only one that should be included :) I guess a bit of misunderstanding.

Comment (judge2005) [reply libraries/SPIFFS/src/SPIFFS.h]: This change requires an additional class, SPIFFFSImpl that inherits VFSImpl, which is declared in vfs_api.h, so something is going to need to include vfs_api.h. Currently this class is declared in SPIFFS.h, which is why SPIFFS.h includes vfs_api.h. How would you have me resolve this?

Comment (me-no-dev) [reply libraries/SPIFFS/src/SPIFFS.h]: Does this class need to be public? What happens if the declaration goes into the CPP file?

Comment (judge2005) [reply libraries/SPIFFS/src/SPIFFS.h]: It should be fine if I move it to the CPP file.

**Comment by me-no-dev** [comment]
merged :)
