### PR TITLE
Fix timerAttachInterrupt() and timerDetachInterrupt() in esp32-hal-timer.c

### LINKED ISSUE #6730: timerAttachInterrupt() and timerDetachInterrupt() broken in 2.0.2+
### Board

ESP32 Dev Module

### Device Description

https://www.banggood.com/ESP32-WiFi-+-bluetooth-Development-Board-Ultra-Low-Power-Consumption-Dual-Core-ESP-32-ESP-32S-Similar-ESP8266-Geekcreit-for-Arduino-products-that-work-with-official-Arduino-boards-p-1175488.html

### Hardware Configuration

16x2 LCD connected via I2C
SD card connected via SDMMC pins
Rotary encoder connected to general IO

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

Windows 10 x64

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Preamble:

After digging through a lot of code in my mission to figure out a resolution to issue #6693 I traced a calls from 2.0.1 through to master,  to see what was happening in the timer code.
While I am no closer to a resolution for that issue, it seems that in the move to IDF, esp32-hal-timer.c has not been completely refactored.

Firstly:
```
void timerAttachInterrupt(hw_timer_t *timer, void (*fn)(void), bool edge){
    if(edge){
        log_w("EDGE timer interrupt is not supported! Setting to LEVEL...");
        edge = false;
    }
    timer_enable_intr(timer->group, timer->num);

    timer_info_t *timer_info = calloc(1, sizeof(timer_info_t));
    timer_info->timer_group = timer->group;
    timer_info->timer_idx = timer->num;
    timer_info->auto_reload = timerGetAutoReload(timer);
    timer_info->alarm_interval = timerAlarmRead(timer);

    timer_isr_callback_add(timer->group, timer->num, (timer_isr_t)fn, timer_info, 0);
}
```
1. `timer_enable_intr(timer->group, timer->num);` is called. This is handled in driver/timer.c in IDF-4.4, so I'm not sure why it's handled here.
2. the `void (*fn)(void)` call back is cast to `timer_isr_t` as `typedef bool (*timer_isr_t)(void *);` so there is no way to allow a yield as specified in the IDF docs (if needed), also the cast seems dodgy.
3. a 'timer_info' struct is allocated, never used and never freed (this would eventually be passed to the callback function, but as per (2) above this is not possible. See `static void IRAM_ATTR timer_isr_default(void *arg)` in driver/timer.c

Secondly:

```
void timerDetachInterrupt(hw_timer_t *timer){
    timerAttachInterrupt(timer, NULL, false);
}
```

This is the previous implementation from pre 2.0.2 code, where passing `NULL` to `timerAttachInterrupt` would effectively undo the attach. See 2.0.1 and previous code in `esp32-hal-timer.c`.

Suggestions:

For `timerAttachInterrupt`:
1. Remove all code except for the edge check and call to `timer_isr_callback_add()`
2. Use an intermediate function of the proper type to wrap `void (*fn)(void)` in a `typedef bool (*timer_isr_t)(void *);`
3. More work may be required here to determine if a yield is necessary

For `timerDetachInterrupt`:
1. Call `timer_isr_callback_remove()`

### Sketch

```cpp
Not applicable
```

### Debug Message

```plain
N/A
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by sweetlilmre**
## Description of Change
This PR fixes the timerAttachInterrupt() and timerDetachInterrupt() functions in esp32-hal-timer.c.

In timerAttachInterrupt() the change:
- removes the unnecessary timer_info_t structure
- removes the allocation of the structure in timerAttachInterrupt()
- removes the call to timer_enable_intr() in timerAttachInterrupt()
- rewords the log message for edge handling (this is not relevant in the IDF4.4 timer driver)
- wraps the ISR function in the correct function type as expected by the IDF4.4 timer driver

Note: to handle the ISR function wrapping a default ISR handler function has been added.

In timerDetachInterrupt() the change:
- removes the previous code
- calls the appropriate function in the IDF4.4 driver

Note: the log message in timerBegin() was also reworded.

## Tests scenarios
I have tested my Pull Request on Arduino-esp32 core master with an ESP32 Board with this scenario

## Related links
Related issue: https://github.com/espressif/arduino-esp32/issues/6730
Closes #6730

### CODE REVIEW

**Comment by me-no-dev** [comment]
@P-R-O-C-H-Y good timing on the timer ci test

**Comment by P-R-O-C-H-Y** [comment]
> @P-R-O-C-H-Y good timing on the timer ci test

Was waiting for the test merge to add the label hil_test there :D

**Comment by sweetlilmre** [comment]
@me-no-dev may I ask what is probably a stupid, but genuine question? :)
How does the master merge that you did work? It looks (from the perspective of my fork) that you merged the main repo master into mine. I'm assuming this is a PR option to rebase my PR on your current master, is that correct?
And I guess it follows that it would be better practise in future to make PR changes in a branch.
Always more to learn. :)

**Comment by me-no-dev** [comment]
@sweetlilmre I updated your branch to have the new changes in our master, which include timer hardware testing. It is more or less rebasing to the upstream master

**Comment by VojtechBartoska** [comment]
@Ouss4 Any clue why the bot didn't show up? :(

**Comment by Ouss4** [comment]
> @Ouss4 Any clue why the bot didn't show up? :(

I talked with Honza regarding this.  I see that the Workflow wasn't triggered at all.  The only thing that's different here is that the OP is a "First time contributor". Github introduced few months ago an approval step required for this situation, I'm not sure how this works for `workflow_runs` (i.e Workflow triggered by another workflow), but my assumption for now is that they require the same "approval" step.
I labeled #6770  from another contributor and the Workflow triggered correctly (Also assuming that the author there was not invited to this repo, if that's the case, I'm gonna have to test with another PR.)

**Comment by sweetlilmre** [comment]
Is there anything I can do to help?

**Comment by sweetlilmre** [comment]
@Ouss4 it looks like my upstream fetch has kicked in the approval behaviour.
Would you mind approving so we can move this PR forward and see if that resolves the previous issue?

**Comment by sweetlilmre** [comment]
@P-R-O-C-H-Y I am excited! :)

File: cores/esp32/esp32-hal-timer.c [hunk 1]
```diff
@@ -194,7 +187,7 @@ static void _on_apb_change(void * arg, apb_change_ev_t ev_type, uint32_t old_apb
 hw_timer_t * timerBegin(uint8_t num, uint16_t divider, bool countUp){
     if(num >= NUM_OF_TIMERS)
     {
-        log_e("Timer dont have that timer number.");
+        log_e("'num' exceeds available number of Timers.");
```
Comment (P-R-O-C-H-Y) [inline cores/esp32/esp32-hal-timer.c:190]: the `'num'` is not printing the num passed to the function.
Please fix it to something like this:
`log_e("Timer number %u exceeds available number of Timers.",num);`

File: cores/esp32/esp32-hal-timer.c [hunk 2]
```diff
@@ -220,24 +213,23 @@ void timerEnd(hw_timer_t *timer){
...
+
+    // some additional logic or handling may be required here to approriately yield or not
+    return false;
+}
+
 void timerAttachInterrupt(hw_timer_t *timer, void (*fn)(void), bool edge){
     if(edge){
-        log_w("EDGE timer interrupt is not supported! Setting to LEVEL...");
-        edge = false;
+        log_w("EDGE timer interrupt is not supported!");
```
Comment (P-R-O-C-H-Y) [inline cores/esp32/esp32-hal-timer.c:226]: I will leave the previous warning log, so user knows that timerAttachInterrupt is set successfully but on LEVEL interrupt. With your change, it can be misunderstood that its not supported so interrupt won't be attached :)

**Review by P-R-O-C-H-Y — CHANGES_REQUESTED** [review]
Thanks for your PR 👍
Please look on comments I made. After fixing these logs, it can be merged :)

File: cores/esp32/esp32-hal-timer.c (hunk 1 above)
Comment (sweetlilmre) [reply cores/esp32/esp32-hal-timer.c]: Fixed.

File: cores/esp32/esp32-hal-timer.c (hunk 2 above)
Comment (sweetlilmre) [reply cores/esp32/esp32-hal-timer.c]: Fixed

**Review by P-R-O-C-H-Y — APPROVED** [review]

**Comment by me-no-dev** [comment]
Thanks @sweetlilmre ! Merged :)

**Comment by sweetlilmre** [comment]
Fantastic! Thank you everyone :)
