### PR TITLE
fix(uart): deals with any combination of inter-UART pin setting

### LINKED ISSUE #12402: [ESP32-S3] UART0 pins cannot be assigned to UART1 or UART2 in 3.3.6 and later
### Board

ESP32-S3 N16R8

### Device Description

Both the ESP32-S3 N16R8 dev kit and a fully custom PCB using the ESP32-S3 N16R8 as a bare microcontroller with no CP2102 bridge chip.

### Hardware Configuration

Board is in USB-CDC mode (pins 19/20 are connected to USB-C port), eFuse `UART_PRINT_CONTROL` is set to `0b11`, eFuse `DIS_PAD_JTAG` is set to `0b1`.

### Version

v3.3.7

### Type

Bug

### IDE Name

Arduino IDE and VSCode with PlatformIO

### Operating System

Windows 10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

(Continued from #12277 and #12386)

On Arduino-ESP32 3.3.6 and later frameworks, pin 43 (by default, UART0 TX) cannot be reassigned to TX for UART1 or UART2. On Arduino-ESP32 3.3.5 or earlier, pin 43 can be reassigned to any UART peripheral on the micro without any issues.

### Sketch

```cpp
#include <Arduino.h>

#define TEST_INTERVAL 5000  // ms between tests
#define BAUD_RATE 115200
#define TEST_TIMEOUT 1000   // ms to wait for response

unsigned long serial1ToSerial0Success = 0;
unsigned long serial1ToSerial0Fail = 0;

unsigned long lastTestTime = 0;

void printUARTStatus(const char* name, HardwareSerial &serial) {
  Serial.printf("\n=== %s Status ===\n", name);
  Serial.printf("  Bytes available to read: %d\n", serial.available());
}

void printStats() {
  Serial.println("\n========== Serial Test Statistics ==========");
  Serial.printf("Serial1 -> Serial0: %lu passed, %lu failed (%.1f%% success)\n",
                serial1ToSerial0Success,
                serial1ToSerial0Fail,
                (serial1ToSerial0Success + serial1ToSerial0Fail) > 0
                  ? (100.0 * serial1ToSerial0Success / (serial1ToSerial0Success + serial1ToSerial0Fail))
                  : 0.0);
  Serial.println("============================================\n");
}

bool testSerialPair(HardwareSerial &sender, HardwareSerial &receiver, const char* direction) {
  static unsigned long testCounter = 0;
  testCounter++;
  String testMessage = String("TEST:") + testCounter + ":" + millis();

  Serial.printf("[%s] Sending: %s\n", direction, testMessage.c_str());

  // Clear receiver buffer
  while (receiver.available()) {
    receiver.read();
  }

  // Send test message
  sender.println(testMessage);
  sender.flush();

  // Debug: Check UART status after sending
  Serial.printf("[%s] After flush, checking receiver status...\n", direction);
  if (strcmp(direction, "S1->S0") == 0) {
    printUARTStatus("Serial0 (receiver)", receiver);
  } else {
    printUARTStatus("Serial1 (receiver)", receiver);
  }

  // Wait for response
  unsigned long startTime = millis();
  String received = "";
  bool success = false;
  int bytesRead = 0;

  while (millis() - startTime < TEST_TIMEOUT) {
    if (receiver.available()) {
      char c = receiver.read();
      bytesRead++;
      if (c == '\n') {
        break;
      }
      if (c != '\r') {
        received += c;
      }
    }
    delay(1);
  }

  // Verify received message
  Serial.printf("[%s] Read %d bytes, received: '%s'\n", direction, bytesRead, received.c_str());

  if (received == testMessage) {
    Serial.printf("[%s] SUCCESS - Message verified\n", direction);
    success = true;
  } else {
    Serial.printf("[%s] FAILED - Expected: %s, Got: %s\n",
                  direction, testMessage.c_str(),
                  received.length() > 0 ? received.c_str() : "(nothing)");
    success = false;
  }

  return success;
}

void setup() {
  setCpuFrequencyMhz(160);
  Serial.begin(115200);
  Serial0.end();

  Serial1.begin(9600, SERIAL_8N1, 44, 43);
  Serial0.begin(9600, SERIAL_8N1, 11, 10);
}

// The main loop of the program which manages all system operations which must occur on every loop.
void loop() {
  unsigned long currentTime = millis();

  if (currentTime - lastTestTime >= TEST_INTERVAL) {
    lastTestTime = currentTime;

    Serial.println("\n--- Testing Serial1 -> Serial0 ---");
    bool success = testSerialPair(Serial1, Serial0, "S1->S0");
    //bool success = testSerialPair(Serial0, Serial1, "S0->S1");
    if (success) {
      serial1ToSerial0Success++;
    } else {
      serial1ToSerial0Fail++;
    }

    if ((serial1ToSerial0Success + serial1ToSerial0Fail) % 2 == 0) {
      printStats();
    }
  }
}
```

### Debug Message

```plain
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-S3
  Package           : 0
  Revision          : 0.02
  Cores             : 2
  CPU Frequency     : 160 MHz
  XTAL Frequency    : 40012
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : No
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   390152 B ( 381.0 KB)
  Free Bytes        :   350972 B ( 342.7 KB)
  Allocated Bytes   :    33596 B (  32.8 KB)
  Minimum Free Bytes:   345824 B ( 337.7 KB)
  Largest Free Block:   294900 B ( 288.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         : 16777216 B (16 MB)
  Block Size        :    65536 B (  64.0 KB)
  Sector Size       :     4096 B (   4.0 KB)
  Page Size         :      256 B (   0.2 KB)
  Bus Speed         : 80 MHz
  Flash Frequency   : 80 MHz (source: 80 MHz, divider: 1)
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1408.0 KB, type: DATA, subtype: SPIFFS
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Feb 23 2026 16:10:07
  Compile Host OS   : windows
  ESP-IDF Version   : v5.5.2-729-g87912cd291
  Arduino Version   : 3.3.7
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32S3_DEV
  Arduino Variant   : esp32s3
  Arduino FQBN      : esp32:esp32:esp32s3:UploadSpeed=921600,USBMode=hwcdc,CDCOnBoot=cdc,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=160,FlashMode=qio,FlashSize=16M,PartitionScheme=default,DebugLevel=debug,PSRAM=disabled,LoopCore=1,EventsCore=1,EraseFlash=none,JTAGAdapter=default,ZigbeeMode=default
============ Before Setup End ============
[  3586][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 19 already has type USB_DM (45) with bus 0x3fc98358
[  3586][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 20 already has type USB_DP (46) with bus 0x3fc98358
[  3587][D][esp32-hal-uart.c:294] _uartDetachBus_RX(): _uartDetachBus_RX: RX pin already detached for UART0
[  3588][D][esp32-hal-uart.c:313] _uartDetachBus_TX(): _uartDetachBus_TX: TX pin already detached for UART0
=========== After Setup Start ============
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   390152 B ( 381.0 KB)
  Free Bytes        :   346228 B ( 338.1 KB)
  Allocated Bytes   :    37796 B (  36.9 KB)
  Minimum Free Bytes:   341080 B ( 333.1 KB)
  Largest Free Block:   294900 B ( 288.0 KB)
------------------------------------------
GPIO Info:
------------------------------------------
  GPIO : BUS_TYPE[bus/unit][chan]
  --------------------------------------  
    10 : UART_TX[0]
    11 : UART_RX[0]
    19 : USB_DM
    20 : USB_DP
    43 : UART_TX[1]
    44 : UART_RX[1]
============ After Setup End =============

--- Testing Serial1 -> Serial0 ---
[S1->S0] Sending: TEST:1:5000
[S1->S0] After flush, checking receiver status...

=== Serial0 (receiver) Status ===
  Bytes available to read: 0
[S1->S0] Read 0 bytes, received: ''
[S1->S0] FAILED - Expected: TEST:1:5000, Got: (nothing)

--- Testing Serial1 -> Serial0 ---
[S1->S0] Sending: TEST:2:10000
[S1->S0] After flush, checking receiver status...

=== Serial0 (receiver) Status ===
  Bytes available to read: 0
[S1->S0] Read 0 bytes, received: ''
[S1->S0] FAILED - Expected: TEST:2:10000, Got: (nothing)

========== Serial Test Statistics ==========
Serial1 -> Serial0: 0 passed, 2 failed (0.0% success)
============================================
```

### Other Steps to Reproduce

Please note that while the debug sketch fails on Arduino-ESP32 3.3.6 and 3.3.7, it will work properly on 3.3.5 and earlier. This is not a hardware problem, nor is it in any way related to devkit boards having a CP2102 bridge chip onboard (our custom hardware has no such bridge chip and experiences the same issue with 3.3.6 and later frameworks).

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change
Previous code was able to change UART pins only when the pins were changed within the same UART number.
Example: `Serial1.begin(115200); Serial1.setPins(1, 2); // changes UART1 to use new pins`

Other situations such as: `Serial1.begin(115200, SERIAL8N1, SOC_RX0, SOC_TX0)` to use the same pins from UART0 and move them to UART1 always fails.

The fail also occurs for more complex cases. such as:
``` cpp
Serial1.begin(115200, SERIAL_8N1, 1, 2);  // UART1 sets pins 1 and 2
Serial2.begin(115200, SERIAL_8N1, 3, 4);  // UART2 sets pins 3 and 4

// UART1 now uses UART2 pins.
// All pins (1 and 2) from UART1 shall be detached
// UART2 must be terminated because it has no valid RX and TX pins anymore
Serial1.setPins(3, 4);
``` 

Another case is moving RX/TX pins to CTS and RTS pins + not setting different one for RX/TX.
It shall terminate the UART because of lack of RX/TX pins.

``` cpp
Serial1.begin(115200, SERIAL_8N1, 1, 2);  // UART1 sets pins 1 and 2
Serial2.begin(115200, SERIAL_8N1, 3, 4);  // UART2 sets pins 3 and 4

Serial2.setPins(-1, -1, 1, 2); // UART1 RX-TX are moved to be UART2 CTS and RTS, therefore UART1 is terminated
```

## Test Scenarios
Tested with this sketch using ESP32-S3:

``` cpp
#include "Wire.h"

void setup() {
  Serial.begin(115200);
  Serial.println();
  Serial.println("Initial Setup: UART1(1,2) + UART2(3, 4)");
  Serial.flush();
  // initial setup
  Serial1.begin(115200, SERIAL_8N1, 1, 2);
  //Serial2.begin(115200, SERIAL_8N1, 3, 4);

  Serial.println("Test Case 0: no change UART1(1,2) -> UART1(1,2)");
  Serial.flush();
  Serial1.setPins(1, 2);
  delay(100);
  Serial.println();

  Serial.println("Test Case 1: Move UART# same pins from UART1(1, 2) -> UART2(1, 2)");
  Serial.flush();
  Serial2.begin(115200, SERIAL_8N1, 1, 2);
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be terminated because its pins are used by UART2 now
  Serial.flush();
  delay(100);
  Serial.println();
  //Serial1.end(); //detach UART1 pins anyway

  Serial.println("Test Case 2: Swap UART2 pins from UART2(1, 2) -> UART2(2, 1)");
  Serial.flush();
  Serial2.setPins(2, 1);
  delay(100);
  Serial.println();

  Serial.println("Test Case 3: Change both pins from UART2(2, 1) -> UART2(5, 6)");
  Serial.flush();
  Serial2.setPins(5, 6);
  delay(100);
  Serial.println();

  Serial.println("Test Case 4: Change RX pin UART2(5, 6) -> UART2(7, 6)");
  Serial.flush();
  Serial2.setPins(7, 6);
  delay(100);
  Serial.println();

  Serial.println("Test Case 5: Change from I2C(7, 6) Terminates UART2 -> UART2(3, 4)");
  Serial.flush();
  Wire.begin(7, 6);  // this shall end Serial2...
  delay(100);
  Serial.printf("Serial2 is running: %s\r\n", Serial2 ? "Yes" : "No");  // Serial 2 shall be terminated because its pins are used by I2C now
  Serial.flush();
  if (Serial2) {
    Serial2.setPins(3, 4);
  } else {
    Serial2.begin(115200, SERIAL_8N1, 3, 4);
  }
  delay(100);
  Serial.println();

  Serial.println("Test Case 6: from UART1 detached to UART1(1, 2)");
  Serial.flush();
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be terminated because its pins are used by UART2 now
  Serial.flush();
  if (Serial1) {
    Serial1.setPins(1, 2);
  } else {
    Serial1.begin(115200, SERIAL_8N1, 1, 2);
  }
  delay(100);
  Serial.println();

  Serial.println("Test Case 7: Multi detaching From UART1(1, 2) + UART2(3, 4) -> UART1(3, 4)");
  Serial.flush();
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be running by Test Case 6
  Serial.printf("Serial2 is running: %s\r\n", Serial2 ? "Yes" : "No");  // Serial 2 shall be running by Test Case 5
  Serial.flush();
  Serial1.setPins(3, 4); // shall detach pins 1, 2 from UART 1 + pins 3 and 4 from UART2 and attach pins 3 and 4 to UART1 
  delay(100);
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be running
  Serial.printf("Serial2 is running: %s\r\n", Serial2 ? "Yes" : "No");  // Serial 2 shall be terminated pins 3 and 4 are now used by UART1
  Serial.println();

  Serial.println("Test Case 8: detaching RX, TX from UART1(3, 4) by moving the pins to CTS and RTS shall end UART1");
  Serial.flush();
  Serial1.setPins(-1, -1, 3, 4); // UART1 has moved its RX, TX pins to be used as CTS and RTS, therefore it shall be terminated
  delay(100);
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be terminated because it lost its RX/TX pins
  Serial.println();

  Serial.println("Test Case 9: detaching RX, TX from UART1(3, 4) by moving the pins to UART2 CTS and RTS (-1, -1, 3, 4) shall end UART1");
  Serial.flush();
  Serial1.begin(115200, SERIAL_8N1, 1, 2); // RX1 = 1 and TX1 = 2
  Serial2.begin(115200, SERIAL_8N1, 3, 4); // RX2 = 3 and TX2 = 4
  Serial2.setPins(-1, -1, 1, 2); // UART1 has no RX1/TX1 pins and shall be terminated, while UART2 has RX2, TX2, CTS2, RTS2
  delay(100);
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be terminated because it lost its RX/TX pins
  Serial.printf("Serial2 is running: %s\r\n", Serial2 ? "Yes" : "No");  // Serial 2 shall be running
  Serial.println();

  Serial.println("Test Case 10: setPins(-1, -1, -1, -1) does nothing - no change");
  Serial.flush();
  Serial1.setPins(-1, -1, -1, -1); // no changes
  delay(100);
  Serial.printf("Serial1 is running: %s\r\n", Serial1 ? "Yes" : "No");  // Serial 1 shall be terminated because it lost its RX/TX pins
  Serial.printf("Serial2 is running: %s\r\n", Serial2 ? "Yes" : "No");  // Serial 2 shall be running
  Serial.println();
  
}

void loop() {
}
```

-------------------------------
### ESP32-S3 Output:

```

ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce2820,len:0x10cc
load:0x403c8700,len:0xc2c
load:0x403cb700,len:0x30c0
entry 0x403c88b8
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-S3
  Package           : 0
  Revision          : 0.01
  Cores             : 2
  CPU Frequency     : 240 MHz
  XTAL Frequency    : 40 MHz
  Features Bitfield : 0x00000012
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : No
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   346120 B ( 338.0 KB)
  Free Bytes        :   312336 B ( 305.0 KB)
  Allocated Bytes   :    29116 B (  28.4 KB)
  Minimum Free Bytes:   307188 B ( 300.0 KB)
  Largest Free Block:   286708 B ( 280.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         :  8388608B (8 MB)
  Block Size        :    65536B (  64.0 KB)
  Sector Size       :     4096B (   4.0 KB)
  Page Size         :      256B (   0.2 KB)
  Bus Speed         : 80 MHz
  Flash Frequency   : 80 MHz (source: 80 MHz, divider: 1)
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1408.0 KB, type: DATA, subtype: SPIFFS
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Apr 10 2026 10:38:08
  Compile Host OS   : windows
  ESP-IDF Version   : v5.5.4
  Arduino Version   : 3.3.7
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32S3_DEV
  Arduino Variant   : esp32s3
  Arduino FQBN      : espressif:orig:esp32s3:UploadSpeed=921600,USBMode=hwcdc,CDCOnBoot=default,MSCOnBoot=default,DFUOnBoot=default,UploadMode=default,CPUFreq=240,FlashMode=qio,FlashSize=4M,PartitionScheme=default,DebugLevel=debug,PSRAM=disabled,LoopCore=1,EventsCore=1,EraseFlash=none,JTAGAdapter=default,ZigbeeMode=default
============ Before Setup End ============
[   369][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 44 to UART0 as RX
[   377][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 43 to UART0 as TX

Initial Setup: UART1(1,2) + UART2(3, 4)
[   388][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 1 to UART1 as RX
[   396][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 2 to UART1 as TX
Test Case 0: no change UART1(1,2) -> UART1(1,2)

Test Case 1: Move UART# same pins from UART1(1, 2) -> UART2(1, 2)
[   514][D][esp32-hal-uart.c:762] _uartDetachConflictingPin(): Detaching pin 1 (RX function) from UART1
[   523][D][esp32-hal-uart.c:762] _uartDetachConflictingPin(): Detaching pin 2 (TX function) from UART1
[   532][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 1 to UART2 as RX
[   539][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 2 to UART2 as TX
[   546][D][esp32-hal-uart.c:885] uartSetPins(): UART1 marked for termination (lost both RX and TX pins)
[   555][D][esp32-hal-uart.c:921] uartSetPins(): Terminating UART1 driver since both RX and TX pins were detached
Serial1 is running: No

Test Case 2: Swap UART2 pins from UART2(1, 2) -> UART2(2, 1)
[   673][D][esp32-hal-uart.c:767] _uartDetachConflictingPin(): Detaching pin 2 (TX function) from UART2 before using as RX
[   684][D][esp32-hal-uart.c:818] uartSetPins(): Detaching old RX pin 1 from UART2
[   691][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 2 to UART2 as RX
[   698][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 1 to UART2 as TX

Test Case 3: Change both pins from UART2(2, 1) -> UART2(5, 6)
[   811][D][esp32-hal-uart.c:818] uartSetPins(): Detaching old RX pin 2 from UART2
[   818][D][esp32-hal-uart.c:825] uartSetPins(): Detaching old TX pin 1 from UART2
[   826][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 5 to UART2 as RX
[   833][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 6 to UART2 as TX

Test Case 4: Change RX pin UART2(5, 6) -> UART2(7, 6)
[   945][D][esp32-hal-uart.c:818] uartSetPins(): Detaching old RX pin 5 from UART2
[   953][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 7 to UART2 as RX

Test Case 5: Change from I2C(7, 6) Terminates UART2 -> UART2(3, 4)
[  1065][D][esp32-hal-uart.c:351] _uartDetachBus_RX(): _uartDetachBus_RX: RX pin already detached for UART2
[  1075][D][esp32-hal-uart.c:374] _uartDetachBus_TX(): _uartDetachBus_TX: both RX and TX pins detached for UART2, terminating driver
[  1087][D][esp32-hal-uart.c:370] _uartDetachBus_TX(): _uartDetachBus_TX: TX pin already detached for UART2
[  1096][I][esp32-hal-i2c-ng.c:112] i2cInit(): Initializing I2C Master: num=0 sda=7 scl=6 freq=100000
Serial2 is running: No
[  1208][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 3 to UART2 as RX
[  1215][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 4 to UART2 as TX

Test Case 6: from UART1 detached to UART1(1, 2)
Serial1 is running: No
[  1329][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 1 to UART1 as RX
[  1336][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 2 to UART1 as TX

Test Case 7: Multi detaching From UART1(1, 2) + UART2(3, 4) -> UART1(3, 4)
Serial1 is running: Yes
Serial2 is running: Yes
[  1454][D][esp32-hal-uart.c:762] _uartDetachConflictingPin(): Detaching pin 3 (RX function) from UART2
[  1464][D][esp32-hal-uart.c:818] uartSetPins(): Detaching old RX pin 1 from UART1
[  1471][D][esp32-hal-uart.c:762] _uartDetachConflictingPin(): Detaching pin 4 (TX function) from UART2
[  1480][D][esp32-hal-uart.c:825] uartSetPins(): Detaching old TX pin 2 from UART1
[  1488][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 3 to UART1 as RX
[  1495][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 4 to UART1 as TX
[  1502][D][esp32-hal-uart.c:885] uartSetPins(): UART2 marked for termination (lost both RX and TX pins)
[  1511][D][esp32-hal-uart.c:921] uartSetPins(): Terminating UART2 driver since both RX and TX pins were detached
Serial1 is running: Yes
Serial2 is running: No

Test Case 8: detaching RX, TX from UART1(3, 4) by moving the pins to CTS and RTS shall end UART1
[  1634][D][esp32-hal-uart.c:767] _uartDetachConflictingPin(): Detaching pin 3 (RX function) from UART1 before using as CTS
[  1645][D][esp32-hal-uart.c:767] _uartDetachConflictingPin(): Detaching pin 4 (TX function) from UART1 before using as RTS
[  1656][D][esp32-hal-uart.c:854] uartSetPins(): Attaching pin 3 to UART1 as CTS
[  1663][D][esp32-hal-uart.c:858] uartSetPins(): Attaching pin 4 to UART1 as RTS
[  1671][D][esp32-hal-uart.c:894] uartSetPins(): UART1 marked for termination (RX/TX pins removed)
[  1679][D][esp32-hal-uart.c:927] uartSetPins(): Terminating UART1 driver since all RX/TX pins were removed and no new pins were set
[  1691][D][esp32-hal-uart.c:389] _uartDetachBus_CTS(): _uartDetachBus_CTS: CTS pin already detached for UART1
[  1701][D][esp32-hal-uart.c:403] _uartDetachBus_RTS(): _uartDetachBus_RTS: RTS pin already detached for UART1
Serial1 is running: No

Test Case 9: detaching RX, TX from UART1(3, 4) by moving the pins to UART2 CTS and RTS (-1, -1, 3, 4) shall end UART1
[  1823][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 1 to UART1 as RX
[  1830][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 2 to UART1 as TX
[  1838][D][esp32-hal-uart.c:846] uartSetPins(): Attaching pin 3 to UART2 as RX
[  1845][D][esp32-hal-uart.c:850] uartSetPins(): Attaching pin 4 to UART2 as TX
[  1852][D][esp32-hal-uart.c:762] _uartDetachConflictingPin(): Detaching pin 1 (RX function) from UART1
[  1861][D][esp32-hal-uart.c:762] _uartDetachConflictingPin(): Detaching pin 2 (TX function) from UART1
[  1870][D][esp32-hal-uart.c:854] uartSetPins(): Attaching pin 1 to UART2 as CTS
[  1877][D][esp32-hal-uart.c:858] uartSetPins(): Attaching pin 2 to UART2 as RTS
[  1885][D][esp32-hal-uart.c:885] uartSetPins(): UART1 marked for termination (lost both RX and TX pins)
[  1894][D][esp32-hal-uart.c:921] uartSetPins(): Terminating UART1 driver since both RX and TX pins were detached
Serial1 is running: No
Serial2 is running: Yes

Test Case 10: setPins(-1, -1, -1, -1) does nothing - no change
Serial1 is running: No
Serial2 is running: Yes

=========== After Setup Start ============
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   346120 B ( 338.0 KB)
  Free Bytes        :   305360 B ( 298.2 KB)
  Allocated Bytes   :    35260 B (  34.4 KB)
  Minimum Free Bytes:   298000 B ( 291.0 KB)
  Largest Free Block:   286708 B ( 280.0 KB)
------------------------------------------
GPIO Info:
------------------------------------------
  GPIO : BUS_TYPE[bus/unit][chan]
  --------------------------------------  
     1 : UART_CTS[2]
     2 : UART_RTS[2]
     3 : UART_RX[2]
     4 : UART_TX[2]
     6 : I2C_MASTER_SCL[0]
     7 : I2C_MASTER_SDA[0]
    43 : UART_TX[0]
    44 : UART_RX[0]
============ After Setup End =============
```

## Related links
Fixes #12402

### CODE REVIEW

File: cores/esp32/esp32-hal-uart.c [hunk 1]
```diff
@@ -705,39 +705,304 @@ bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, in
...
+      log_i("Terminating UART%d driver since both RX and TX pins were detached", rxPinPrevUART);
+      hardware_serial_end(rxPinPrevUART);
+    }
+  }
+  if (txPin >= 0 && txPinPrevUART >= 0 && txPinPrevUART != uart_num && txPinPrevUART != rxPinPrevUART) {
+    // txPin was detached from a different UART (and not the same one already checked for rxPin)
+    uart_t *prevUart = &_uart_bus_array[txPinPrevUART];
+    if (prevUart->_rxPin < 0 && prevUart->_txPin < 0) {
+      log_i("Terminating UART%d driver since both RX and TX pins were detached", txPinPrevUART);
+      hardware_serial_end(txPinPrevUART);
```
[the remark this answers is not in the document]
Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: UART termination is only related to no attached RX/TX pins.

File: cores/esp32/esp32-hal-uart.c [hunk 2]
```diff
@@ -705,39 +705,304 @@ bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, in
...
+
+    // Attach is needed if: pin is not already assigned as RX to this UART
+    rxAttach = rxPinPeripheralType != ESP32_BUS_TYPE_UART_RX || uart_num != rxPinPrevUART;
+
+    // Detach is needed if: pin is already in use by a UART OR if we're replacing the old RX pin
+    rxDetach = rxPinIsPeriTypeUART || (rxPin != uart->_rxPin && uart->_rxPin >= 0);
+
+    log_i("RX: pin %d -> UART%d: currently [%s in UART%d], attach=%s, detach=%s", 
+          rxPin, uart_num, rxPinIsPeriTypeUART ? "UART" : "GPIO", rxPinPrevUART, rxAttach ? "YES" : "NO", rxAttach && rxDetach ? "YES" : "NO");
+  }
```
[the remark this answers is not in the document]
Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: solved.

File: cores/esp32/esp32-hal-uart.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: @copilot - review this again basd on the last commit done.

File: cores/esp32/esp32-hal-uart.c [hunk 3]
```diff
@@ -705,39 +705,304 @@ bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, in
...
+
+  // Check termination: Only terminate UARTs that lost both RX/TX pins AND don't have new pins being set
+  // Check the UARTs that had RX or TX pins detached from them
+  if (rxPin >= 0 && rxPinPrevUART >= 0 && rxPinPrevUART != uart_num) {
+    // rxPin was detached from a different UART
+    uart_t *prevUart = &_uart_bus_array[rxPinPrevUART];
+    if (prevUart->_rxPin < 0 && prevUart->_txPin < 0) {
+      log_i("Terminating UART%d driver since both RX and TX pins were detached", rxPinPrevUART);
+      hardware_serial_end(rxPinPrevUART);
+    }
```
[the remark this answers is not in the document]
Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: @copilot - review this again basd on the last commit done.

File: cores/esp32/esp32-hal-uart.c [hunk 4]
```diff
@@ -705,39 +705,304 @@ bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, in
...
+
+    log_i("RTS: pin %d -> UART%d: currently [%s in UART%d], attach=%s, detach=%s",
+          rtsPin, uart_num, rtsPinIsPeriTypeUART ? "UART" : "GPIO", rtsPinPrevUART, rtsAttach ? "YES" : "NO", rtsAttach && rtsDetach ? "YES" : "NO");
+  }
+
+  // First step: detaches all pins that conflict
+  // Handle RX pin: detach both the new pin (if in use) and the old pin (if being replaced)
+  if (rxPin >= 0) {
+    rxPinPeripheralType = perimanGetPinBusType(rxPin);
+    bool rxPinIsPeriTypeUART = rxPinPeripheralType >= ESP32_BUS_TYPE_UART_RX && rxPinPeripheralType <= ESP32_BUS_TYPE_UART_RTS;
```
[the remark this answers is not in the document]
Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: @copilot - review this again basd on the last commit done.

**Comment by SuGlider** [comment]
@copilot - consider the issue description about the test case code and suggest improvement with newer test cases

File: cores/esp32/esp32-hal-uart.c [hunk 5]
```diff
@@ -705,39 +705,328 @@ bool uartSetPins(uint8_t uart_num, int8_t rxPin, int8_t txPin, int8_t ctsPin, in
...
+
+    log_v("RTS: pin %d -> UART%d: currently [%s in UART%d], attach=%s",
+          rtsPin, uart_num, rtsPinIsPeriTypeUART ? "UART" : "GPIO", rtsPinPrevUART, rtsAttach ? "YES" : "NO");
+  }
+
+  // First step: detaches all pins that conflict
+  // Handle RX pin: detach both the new pin (if in use) and the old pin (if being replaced)
+  if (rxPin >= 0) {
+    rxPinPeripheralType = perimanGetPinBusType(rxPin);
+    bool rxPinIsPeriTypeUART = rxPinPeripheralType >= ESP32_BUS_TYPE_UART_RX && rxPinPeripheralType <= ESP32_BUS_TYPE_UART_RTS;
```
[the remark this answers is not in the document]
Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: @copilot compute and suggest changes based on [this feedback](https://github.com/espressif/arduino-esp32/pull/12512#discussion_r3065686127)

File: cores/esp32/esp32-hal-uart.c [hunk 6]
```diff
@@ -678,6 +678,55 @@ bool uartIsDriverInstalled(uart_t *uart) {
...
+
+  if (prevUART != target_uart_num) {
+    log_d("Detaching pin %d (%s function) from UART%d", pin, currentFuncName, prevUART);
+    if (prevOtherUARTOut != NULL) {
+      *prevOtherUARTOut = prevUART;
+    }
+  } else {
+    log_d("Detaching pin %d (%s function) from UART%d before using as %s", pin, currentFuncName, prevUART, target_func_name);
+  }
+  return _uartDetachPins(prevUART, d_rx, d_tx, d_cts, d_rts);
```
Comment (SuGlider) [inline cores/esp32/esp32-hal-uart.c:769]:
```suggestion
  (void)currentFuncName;  // Suppress unused variable warning when log_d is compiled out
  return _uartDetachPins(prevUART, d_rx, d_tx, d_cts, d_rts);
```

File: cores/esp32/esp32-hal-uart.c [hunk 7]
```diff
@@ -678,6 +678,57 @@ bool uartIsDriverInstalled(uart_t *uart) {
...
+  if (prevUART != target_uart_num) {
+    log_d("Detaching pin %d (%s function) from UART%d", pin, currentFuncName, prevUART);
+    if (prevOtherUARTOut != NULL) {
+      *prevOtherUARTOut = prevUART;
+    }
+  } else {
+    log_d("Detaching pin %d (%s function) from UART%d before using as %s", pin, currentFuncName, prevUART, target_func_name);
+  }
+  (void)currentFuncName;  // Suppress unused variable warning when log_d is compiled out
+  (void)currentFuncName;  // Suppress unused variable warning when log_d is compiled out
```
Comment (SuGlider) [inline cores/esp32/esp32-hal-uart.c]:
```suggestion
  (void)currentFuncName;  // Suppress unused variable warning when log_d is compiled out
```

**Comment by SuGlider** [comment]
@copilot - The new CI code fails with this run time message:
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:195:same_uart_pin_swap_test:FAIL: Expected 'Hello from Serial1 after pin swap' Was ''

Fix it.

File: tests/validation/uart/uart.ino [hunk 8]
```diff
@@ -1,3 +1,4 @@
+
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
```

File: tests/validation/uart/uart.ino [hunk 9]
```diff
@@ -91,7 +91,12 @@ public:
     }
     while (available--) {
       c = (char)serial.read();
-      recv_msg += c;
+      if (c >= 32 && c <= 128) {
+        recv_msg += c;
+      } else {
+        Serial.printf("UART%d onReceive() got a non readable character 0x%x='%c'\r\n", uart_num, c, c);
+        Serial.flush();
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
//      } else {
//        Serial.printf("UART%d onReceive() got a non readable character 0x%x='%c'\r\n", uart_num, c, c);
//        Serial.flush();
```

File: tests/validation/uart/uart.ino [hunk 10]
```diff
@@ -594,6 +706,9 @@ void setup() {
 
   log_d("Setup done. Starting tests");
 
+  Serial.println("UART_TEST_READY");
+  Serial.flush();
+
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
```

File: tests/validation/uart/uart.ino [hunk 11]
```diff
@@ -73,10 +73,10 @@ public:
 
   void transmit_and_check_msg(const String &msg_append, bool perform_assert = true) {
     reset_buffers();
-    delay(100);
+    delay(2);
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
    delay(50);
```

File: tests/validation/uart/uart.ino [hunk 12]
```diff
@@ -73,10 +73,10 @@ public:
...
     serial.print("Hello from Serial" + String(uart_num) + " " + msg_append);
     serial.flush();
-    delay(100);
+    delay(10);
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
    delay(50);
```

File: tests/validation/uart/uart.ino [hunk 13]
```diff
@@ -114,7 +119,7 @@ extern "C" int8_t uart_get_TxPin(uint8_t uart_num);
 // This task is used to send a message after a delay to test the auto baudrate detection
 void task_delayed_msg(void *pvParameters) {
   HardwareSerial &selected_serial = uart_test_configs.size() == 1 ? Serial : Serial1;
-  delay(2000);
+  delay(1000);
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
  delay(1500);
```

File: tests/validation/uart/uart.ino [hunk 14]
```diff
@@ -535,7 +540,7 @@ void hardware_flow_control_test(void) {
     uart_internal_loopback(config.uart_num, config.default_rx_pin);
     uart_internal_hw_flow_ctrl_loopback(config.uart_num, TEST_CTS_PIN);
 
-    delay(100);
+    delay(10);
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
    delay(50);
```

File: tests/validation/uart/uart.ino [hunk 15]
```diff
@@ -544,13 +549,120 @@ void hardware_flow_control_test(void) {
     TEST_ASSERT_TRUE(flow_ctrl_disabled);
 
     // Test transmission still works after disabling flow control
-    delay(100);
+    delay(10);
```
Comment (SuGlider) [inline tests/validation/uart/uart.ino]:
```suggestion
    delay(50);
```

**Review by SuGlider — COMMENTED** [review]
Reversing some waiting time to an average lower value

**Comment by SuGlider** [comment]
@lucasssvaz @me-no-dev  - CI Test Results using the actual SoC (ESP32/ESP32-S3):

## ESP32:
```
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4876
ho 0 tail 12 room 4
load:0x40078000,len:16560
load:0x40080400,len:3500
entry 0x400805b4
Begin when running test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:836:begin_when_running_test:PASS
Basic transmission test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:837:basic_transmission_test:PASS
[   135][E][HardwareSerial.cpp:661] setRxBufferSize(): RX Buffer can't be resized when Serial is already running. Set it before calling begin().
[   148][E][HardwareSerial.cpp:680] setTxBufferSize(): TX Buffer can't be resized when Serial is already running. Set it before calling begin().
Buffer resize test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:838:resize_buffers_test:PASS
Change baudrate test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:839:change_baudrate_test:PASS
Change CPU frequency test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:840:change_cpu_frequency_test:PASS
Disabled UART calls test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:841:disabled_uart_calls_test:PASS
Enabled UART calls test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:842:enabled_uart_calls_test:PASS
Auto baudrate test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:844:auto_baudrate_test:PASS
Peripheral manager test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:846:periman_test:PASS
Change pins test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:847:change_pins_test:PASS
Hardware flow control test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:848:hardware_flow_control_test:PASS
Inter-UART pin move test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:849:inter_uart_pin_move_test:PASS
Same UART pin swap test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:850:same_uart_pin_swap_test:PASS
Move RX/TX to CTS/RTS terminates UART test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:851:move_rx_tx_to_cts_rts_test:PASS
Cross-UART CTS/RTS terminates source UART test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:852:cross_uart_cts_rts_test:PASS
End when stopped test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:853:end_when_stopped_test:PASS

-----------------------
16 Tests 0 Failures 0 Ignored 
OK
```

-------------------------------
## ESP32-S3:
```
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fce2820,len:0x10cc
load:0x403c8700,len:0xc2c
load:0x403cb700,len:0x30c0
entry 0x403c88b8
Begin when running test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:836:begin_when_running_test:PASS
Basic transmission test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:837:basic_transmission_test:PASS
[   113][E][HardwareSerial.cpp:661] setRxBufferSize(): RX Buffer can't be resized when Serial is already running. Set it before calling begin().
[   125][E][HardwareSerial.cpp:680] setTxBufferSize(): TX Buffer can't be resized when Serial is already running. Set it before calling begin().
Buffer resize test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:838:resize_buffers_test:PASS
Change baudrate test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:839:change_baudrate_test:PASS
Change CPU frequency test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:840:change_cpu_frequency_test:PASS
Disabled UART calls test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:841:disabled_uart_calls_test:PASS
Enabled UART calls test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:842:enabled_uart_calls_test:PASS
Peripheral manager test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:846:periman_test:PASS
Change pins test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:847:change_pins_test:PASS
Hardware flow control test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:848:hardware_flow_control_test:PASS
Inter-UART pin move test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:849:inter_uart_pin_move_test:PASS
Same UART pin swap test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:850:same_uart_pin_swap_test:PASS
Move RX/TX to CTS/RTS terminates UART test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:851:move_rx_tx_to_cts_rts_test:PASS
Cross-UART CTS/RTS terminates source UART test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:852:cross_uart_cts_rts_test:PASS
End when stopped test successful
C:\Users\esp\Documents\Arduino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino\issue_12402_Extended_Test_Cases_UART1_using_RX0_TX0.ino.ino:853:end_when_stopped_test:PASS

-----------------------
15 Tests 0 Failures 0 Ignored 
OK
```

**Review by me-no-dev — APPROVED** [review]
