### PR TITLE
fix(ble): Fix Advertising race condition

### LINKED ISSUE #12437: Bluetooth stack stops after BLE disconnect
### Board

ESP32 Dev Module

### Device Description

common Chinese ESP32 board from aliexpress, just a board, nothing attached to it

### Hardware Configuration

nothing except on-board LED (GPIO 2) is connected

### Version

v3.3.7

### Type

Bug

### IDE Name

Arduino IDE

### Operating System

Linux, Ubuntu-based, Ubuntu 24.04

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

after disconnecting from BLE device becomes invisible regardless that device reports that it started advertising, classic BT dies too (if present).

seems the whole BT stack stops (at least no new audio data received through A2DP sink), but classic BT connection doesn't seems to be lost (and doesn't cause any issues on the source side).

issue appeared with 3.3.7, 3.3.6 and below works ok. only BLE stack affected, disconnecting from classic BT stack (A2DP sink) doesn't cause the issue.

### Sketch

```cpp
#include <BLEDevice.h>
#include <BLEUtils.h>
#include <BLEServer.h>

// See the following for generating UUIDs:
// https://www.uuidgenerator.net/

#define SERVICE_UUID        "4fafc201-1fb5-459e-8fcc-c5c9c331914b"
#define CHARACTERISTIC_UUID "beb5483e-36e1-4688-b7f5-ea07361b26a8"

class MyServerCallbacks: public BLEServerCallbacks
{
  void onConnect(BLEServer* pServer)
  {
  }

  void onDisconnect(BLEServer* pServer)
  {
    // pServer->startAdvertising();
    BLEDevice::startAdvertising();
  }
};

void setup() {
  Serial.begin(115200);
  Serial.println("Starting BLE work!");

  BLEDevice::init("Long name works now");
  BLEServer *pServer = BLEDevice::createServer();
  pServer->setCallbacks(new MyServerCallbacks);
  BLEService *pService = pServer->createService(SERVICE_UUID);
  BLECharacteristic *pCharacteristic =
    pService->createCharacteristic(CHARACTERISTIC_UUID, BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_WRITE);

  pCharacteristic->setValue("Hello World says Neil");
  pService->start();
  // BLEAdvertising *pAdvertising = pServer->getAdvertising();  // this still is working for backward compatibility
  BLEAdvertising *pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->addServiceUUID(SERVICE_UUID);
  pAdvertising->setScanResponse(true);
  pAdvertising->setMinPreferred(0x06);  // functions that help with iPhone connections issue
  pAdvertising->setMaxPreferred(0x12);
  BLEDevice::startAdvertising();
  Serial.println("Characteristic defined! Now you can read it in your phone!");
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(2000);
}

// this is minimal example enough to reproduce the issue,
// real code where I faced the issue also uses classic BT stack as A2DP sink,
// but this is not important.
```

### Debug Message

```plain
ets Jul 29 2019 12:21:46

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4876
ho 0 tail 12 room 4
load:0x40078000,len:16560
load:0x40080400,len:3500
entry 0x400805b4
[    28][D][esp32-hal-cpu.c:316] setCpuFrequencyMhz(): PLL: 480 / 2 = 240 Mhz, APB: 80000000 Hz
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32
  Package           : D0WD-Q5
  Revision          : 3.01
  Cores             : 2
  CPU Frequency     : 240 MHz
  XTAL Frequency    : 40 MHz
  Features Bitfield : 0x00000032
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : Yes
  BT Low Energy     : Yes
  IEEE 802.15.4     : No
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   266580 B ( 260.3 KB)
  Free Bytes        :   227212 B ( 221.9 KB)
  Allocated Bytes   :    33808 B (  33.0 KB)
  Minimum Free Bytes:   222200 B ( 217.0 KB)
  Largest Free Block:   110580 B ( 108.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         :  4194304 B (4 MB)
  Block Size        :    65536 B (  64.0 KB)
  Sector Size       :     4096 B (   4.0 KB)
  Page Size         :      256 B (   0.2 KB)
  Bus Speed         : 80 MHz
  Flash Frequency   : 80 MHz (source: 80 MHz, divider: 1)
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1408.0 KB, type: DATA, subtype: SPIFFS
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Mar 10 2026 09:59:40
  Compile Host OS   : linux
  ESP-IDF Version   : v5.5.2-729-g87912cd291
  Arduino Version   : 3.3.7
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32_DEV
  Arduino Variant   : esp32
  Arduino FQBN      : esp32:esp32:esp32:UploadSpeed=921600,CPUFreq=240,FlashFreq=80,FlashMode=qio,FlashSize=4M,PartitionScheme=default,DebugLevel=debug,PSRAM=disabled,LoopCore=1,EventsCore=1,EraseFlash=none,JTAGAdapter=default,ZigbeeMode=default
============ Before Setup End ============
Starting BLE work!
[   545][I][BLEDevice.cpp:274] init(): Initializing BLE stack: Bluedroid
[  1236][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_REG_EVT
[  1247][I][BLEServer.cpp:579] handleGATTServerEvent(): GATT server registered, status=0, app_id=0, gatts_if=4
[  1258][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_CREATE_EVT
[  1269][D][BLEService.cpp:238] addCharacteristic(): Adding characteristic: uuid=beb5483e-36e1-4688-b7f5-ea07361b26a8 to service: UUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b, handle: 0x0028
[  1286][D][BLECharacteristic.cpp:211] executeCreate(): Registering characteristic (esp_ble_gatts_add_char): uuid: beb5483e-36e1-4688-b7f5-ea07361b26a8, service: UUID: 4fafc201-1fb5-459e-8fcc-c5c9c331914b, handle: 0x0028
[  1306][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_ADD_CHAR_EVT
[  1317][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_START_EVT
[  1328][I][BLEDevice.cpp:850] getAdvertising(): create advertising
[  1331][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[  1340][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[  1340][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 17]
[  1353][I][BLEAdvertising.cpp:795] handleGAPEvent(): STOP advertising
[  1353][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[  1365][D][BLEAdvertising.cpp:691] start(): - advertising service: 4fafc201-1fb5-459e-8fcc-c5c9c331914b
[  1378][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[  1384][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 0]
[  1391][D][BLEAdvertising.cpp:778] handleGAPEvent(): Advertising data set complete, status=0
[  1399][D][BLEAdvertising.cpp:717] start(): Advertising data configured
[  1408][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[  1414][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 1]
[  1422][D][BLEAdvertising.cpp:784] handleGAPEvent(): Scan response data set complete, status=0
[  1430][D][BLEAdvertising.cpp:738] start(): Scan response data configured
Characteristic defined! Now you can read it in your phone!
=========== After Setup Start ============
[  1445][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[  1451][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 6]
INTERNAL Memory Info:
------------------------------------------
[  1461][D][BLEAdvertising.cpp:790] handleGAPEvent(): Advertising start complete, status=0
  Total Size        :   266580 B ( 260.3 KB)
  Free Bytes        :   133200 B ( 130.1 KB)
  Allocated Bytes   :   122732 B ( 119.9 KB)
  Minimum Free Bytes:   132824 B ( 129.7 KB)
  Largest Free Block:   110580 B ( 108.0 KB)
------------------------------------------
GPIO Info:
------------------------------------------
  GPIO : BUS_TYPE[bus/unit][chan]
  --------------------------------------
     1 : UART_TX[0]
     3 : UART_RX[0]
============ After Setup End =============
[ 16137][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_CONNECT_EVT
[ 16150][I][BLEServer.cpp:489] handleGATTServerEvent(): Client connected, conn_id=0
[ 16158][D][BLEServer.cpp:630] onConnect(): BLEServerCallbacks
[ 16163][D][BLEServer.cpp:631] onConnect(): BLEServerCallbacks
[ 16169][D][BLEServer.cpp:632] onConnect(): BLEServerCallbacks
[ 16224][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[ 16230][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 21]
[ 16854][I][BLEDevice.cpp:1265] gapEventHandler(): ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT: status=0, conn_int=30, latency=0, timeout=400
[ 16866][D][BLEServer.cpp:690] onConnParamsUpdate(): BLEServerCallbacks
[ 16872][D][BLEServer.cpp:691] onConnParamsUpdate(): BLEServerCallbacks
[ 16879][D][BLEServer.cpp:695] onConnParamsUpdate(): BLEServerCallbacks
[ 16885][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[ 16891][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 20]
[ 17312][I][BLEDevice.cpp:1265] gapEventHandler(): ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT: status=0, conn_int=6, latency=0, timeout=500
[ 17324][D][BLEServer.cpp:690] onConnParamsUpdate(): BLEServerCallbacks
[ 17330][D][BLEServer.cpp:691] onConnParamsUpdate(): BLEServerCallbacks
[ 17337][D][BLEServer.cpp:695] onConnParamsUpdate(): BLEServerCallbacks
[ 17344][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[ 17350][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 20]
[ 17522][I][BLEDevice.cpp:1265] gapEventHandler(): ESP_GAP_BLE_UPDATE_CONN_PARAMS_EVT: status=0, conn_int=30, latency=0, timeout=400
[ 17533][D][BLEServer.cpp:690] onConnParamsUpdate(): BLEServerCallbacks
[ 17540][D][BLEServer.cpp:691] onConnParamsUpdate(): BLEServerCallbacks
[ 17546][D][BLEServer.cpp:695] onConnParamsUpdate(): BLEServerCallbacks
[ 17553][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[ 17558][D][BLEAdvertising.cpp:773] handleGAPEvent(): handleGAPEvent [event no: 20]
[ 20200][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_READ_EVT
[ 20210][D][BLECharacteristic.cpp:700] handleGATTServerEvent(): mtu value: 22
[ 20217][D][BLECharacteristic.cpp:702] handleGATTServerEvent(): Sending a response (esp_ble_gatts_send_response)
[ 20227][D][BLECharacteristic.cpp:458] onRead(): >> onRead: default
[ 20233][D][BLECharacteristic.cpp:459] onRead(): << onRead
[ 20239][D][BLECharacteristic.cpp:749] handleGATTServerEvent():  - Data: length=21, data=48656c6c6f20576f726c642073617973204e65696c, offset=0
[ 20252][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_RESPONSE_EVT
[ 23424][D][BLEDevice.cpp:1071] gattServerEventHandler(): gattServerEventHandler [esp_gatt_if: 4] ... ESP_GATTS_DISCONNECT_EVT
[ 23436][I][BLEServer.cpp:529] handleGATTServerEvent(): Client disconnected, conn_id=0, reason=19
[ 23444][D][BLEDevice.cpp:852] getAdvertising(): get advertising
[ 23450][D][BLEAdvertising.cpp:691] start(): - advertising service: 4fafc201-1fb5-459e-8fcc-c5c9c331914b
```

### Other Steps to Reproduce

1. flash given **modified** (with re-advertising logic) example sketch
2. connect to the device using any BLE client app (I used [nRF Connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&hl=en-US) on Android)
3. disconnect from device
4. scan for available BLE devices -> no more device visible

attached logs demonstrate working (3.3.6) and non-working (3.3.7) cases:
[ble-3.3.6-log.txt](https://github.com/user-attachments/files/25865762/ble-3.3.6-log.txt)
[ble-3.3.7-log.txt](https://github.com/user-attachments/files/25865765/ble-3.3.7-log.txt)

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by lucasssvaz**
## Description of Change

This pull request enhances the robustness of BLE advertising state management by introducing a new `m_advertisingPending` flag in the `BLEAdvertising` class. This flag tracks whether an advertising start request is pending, improving handling of advertising restarts, retries on failure, and synchronization with GAP events. The changes help prevent missed or duplicate advertising start attempts, especially in edge cases involving quick stop/start sequences or advertising failures.

Key changes:

**State Management Improvements:**

* Added a new `m_advertisingPending` boolean member to the `BLEAdvertising` class to track when advertising has been requested but not yet confirmed by the GAP event. (`libraries/BLE/src/BLEAdvertising.h`, `libraries/BLE/src/BLEAdvertising.cpp`) [[1]](diffhunk://#diff-9f70280c82176e6107913110e657532f77ce16f4dd83f6e75e5cffb94bd50f86R226) [[2]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R677)

**Advertising Start/Stop Logic:**

* Set `m_advertisingPending` to `true` when starting advertising and reset it to `false` on failure or when advertising is stopped, ensuring accurate tracking of pending advertising operations. (`BLEAdvertising::start`, `BLEAdvertising::stop`) [[1]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R998-R1001) [[2]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R1016)

**GAP Event Handling Enhancements:**

* Updated `handleGAPEvent` to properly set or clear `m_advertisingPending` during various advertising-related events, including retries on advertising start failure and automatic restarts if advertising was stopped before the start completed. (`handleGAPEvent`) [[1]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R1051-R1054) [[2]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R1075-R1078) [[3]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R1102-R1105) [[4]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R1123-R1126) [[5]](diffhunk://#diff-fddee4cf110e9c6f997182d84232abc70ee46367b93c3ae7891711b3b637d5d7R1135-R1161)

These improvements ensure more reliable and predictable BLE advertising behavior, particularly in scenarios where advertising operations are requested in rapid succession or encounter errors.

## Related links

Closes #12437

### CODE REVIEW

File: libraries/BLE/src/BLEAdvertising.cpp [hunk 1]
```diff
@@ -1120,11 +1132,33 @@ void BLEAdvertising::handleGAPEvent(esp_gap_ble_cb_event_t event, esp_ble_gap_cb
...
+        }
+      }
       break;
     }
     case ESP_GAP_BLE_ADV_STOP_COMPLETE_EVT:
     {
       log_i("STOP advertising");
+      m_advConfiguring = false;  // Clear configuring flag so start() can be called again
+      // If a start was requested but advertising was stopped (e.g., due to a connection) before
+      // the start complete event fired, re-issue start_advertising to honour the request.
```
Comment (lucasssvaz) [inline libraries/BLE/src/BLEAdvertising.cpp]:
```suggestion
      // the start complete event fired, re-issue start_advertising to honor the request.
```
