### PR TITLE
fixes BLE HID Battery Level Indicator

### LINKED ISSUE #6708: function setBatteryLevel()  in BLEHIDDevice.cpp is invalid
### Board

ESP32 DevModule

### Device Description

a ble keyboard use ESP32 DevModule

### Hardware Configuration

BLE Server

### Version

v2.0.2

### IDE Name

arduino ide

### Operating System

win10

### Flash frequency

40MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

BLEHIDDevice hid;
hid->setBatteryLevel(level);    

esp32实现的蓝牙键盘(server 模式)，用这种方法进行电量设置，在win10系统下显示键盘电量。
在初次连接时，电量显示正常，电量也可变化。但是断开连接后重新连接，电量始终显示为初次连接时的电量，且更改变量赋值后，win10系统显示变量仍然无变化。

I want to use this way to make my BLE keyboard change battery level in win10. but it is invalid.
When I connect my keyboard first time, it is work, meanwhile, win10 can show my real-time battery level.
but after disconnect and reconnect, win10 can only show its last battery level, and can't show my realt-ime battery level, when I change my battery level variable.

### Sketch

```cpp
BLEHIDDevice hid;
hid->setBatteryLevel(level);
```

### Debug Message

```plain
no debug message
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change
BLE HID uses GATT Service to send Battery Level Indication.
It works fine on first time pairing and bonding, but on reconnect it doesn't update the Battery Level characteristic anymore. 
It is fixed by setting the Notification to be ON, by default at the Service Creation. 

## Tests scenarios
Tested with ESP32 using Bluedroid and NimBLE.

## Related links
Fixes #6708

### CODE REVIEW

File: libraries/BLE/src/BLEHIDDevice.cpp [hunk 1]
```diff
@@ -42,7 +42,10 @@ BLEHIDDevice::BLEHIDDevice(BLEServer* server) {
 
 	m_batteryLevelCharacteristic = m_batteryService->createCharacteristic((uint16_t) 0x2a19, BLECharacteristic::PROPERTY_READ | BLECharacteristic::PROPERTY_NOTIFY);
 	m_batteryLevelCharacteristic->addDescriptor(batteryLevelDescriptor);
-	m_batteryLevelCharacteristic->addDescriptor(new BLE2902());
+    BLE2902 *batLevelIndicator = new BLE2902();
```
Comment (me-no-dev) [inline libraries/BLE/src/BLEHIDDevice.cpp:45]: indentation seems wrong here :)
