### PR TITLE
fix(rmt): forces enabling reading channel

### LINKED ISSUE #12267: rmtRead() generates errors if first call was unsuccessfull
### Board

ESP32-S3 DevKit Clone

### Device Description

8 mb OPI ram, 16mb flash

### Hardware Configuration

GPIO2 is connected to GPIO4

### Version

v3.3.5

### Type

Bug

### IDE Name

Arduino IDE

### Operating System

Win10

### Flash frequency

80MHz

### PSRAM enabled

yes

### Upload speed

115200

### Description

If first call to rmtRead() fails (i.e. function return "false", zero symbols received) then all subsequent calls to rmtRead() says that "channel is not in enabled state"

```
[ 21299][V][esp32-hal-rmt.c:490] rmtInit(): GPIO 2 - RX MODE - MemSize[96] - Freq=1000000Hz
[ 21299][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type RMT_TX (10) successfully set to 0x42018a48
[ 21300][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type RMT_RX (11) successfully set to 0x42018a48
[ 21301][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 2 successfully set to type RMT_RX (11) with bus 0x3c1309e4
[ 21302][V][esp32-hal-rmt.c:391] _rmtRead(): GPIO: 2 - Request: 1024 RMT Symbols - Blocking - Timeout: 2000

% RMT failed to rmtRead --- my debug output
```
Second attempt:
```
[ 28501][V][esp32-hal-rmt.c:490] rmtInit(): GPIO 2 - RX MODE - MemSize[96] - Freq=1000000Hz
[ 28502][V][esp32-hal-rmt.c:391] _rmtRead(): GPIO: 2 - Request: 1024 RMT Symbols - Blocking - Timeout: 2000
E (28475) rmt: rmt_receive(401): channel not in enable state
```

### Sketch

```cpp
The sketch itself is too complicated, but the function it uses is


...
....
  uint32_t timo = 2000;
  size_t rbuf_size = 1024;
  rmt_data_t *rbuf = (rmt_data_t *)malloc(sizeof(rmt_data_t) * rbuf_size);

  if (!rbuf)
    return false;

  if (rmtInit(2, RMT_RX_MODE, RMT_MEM_NUM_BLOCKS_2, 10000000)) {
    // Apply some settings
    if (rmtSetCarrier(2, false, false, 0, 0)) {
      // Receive data (blocking call)                            
      if (rmtRead(pin, rbuf, &rbuf_size, timo == 0 ? RMT_WAIT_FOR_EVER : timo)) {
...
...
```

### Debug Message

```plain
First call to rmtRead() (failed, because there was no data on the RX pin):


[ 21299][V][esp32-hal-rmt.c:490] rmtInit(): GPIO 2 - RX MODE - MemSize[96] - Freq=1000000Hz
[ 21299][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type RMT_TX (10) successfully set to 0x42018a48
[ 21300][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type RMT_RX (11) successfully set to 0x42018a48
[ 21301][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 2 successfully set to type RMT_RX (11) with bus 0x3c1309e4
[ 21302][V][esp32-hal-rmt.c:391] _rmtRead(): GPIO: 2 - Request: 1024 RMT Symbols - Blocking - Timeout: 2000

% RMT failed to rmtRead --- my debug output


Second attempt:


[ 28501][V][esp32-hal-rmt.c:490] rmtInit(): GPIO 2 - RX MODE - MemSize[96] - Freq=1000000Hz
[ 28502][V][esp32-hal-rmt.c:391] _rmtRead(): GPIO: 2 - Request: 1024 RMT Symbols - Blocking - Timeout: 2000
E (28475) rmt: rmt_receive(401): channel not in enable state
```

### Other Steps to Reproduce

Standart example "Examples->ESP32->EMT->RMTReadXJT" just compile and run without providing any input.

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Description of Change

Added logic to stop and restart RMT channel for data reading in blocking mode.

## Test Scenarios

Tested using ESP32-S3 and this sketch:

``` cpp
rmt_data_t *rbuf = NULL;
size_t rbuf_size = 1024;
const uint8_t rmtPin = 2;

void setup() {
  Serial.begin(115200);
  Serial.setDebugOutput(true);
  delay(3000);
  rbuf = (rmt_data_t *)malloc(sizeof(rmt_data_t) * rbuf_size);
}

void loop() {
  const uint32_t rmt_timeout = 2000;

  if (!rbuf) {
    Serial.println("rbuf is NULL... malloc failed.");
  } else {
    // init and read RMT channel
    if (rmtInit(rmtPin, RMT_RX_MODE, RMT_MEM_NUM_BLOCKS_2, 10000000)) {
        rbuf_size = 1024;
        if (rmtRead(rmtPin, rbuf, &rbuf_size, rmt_timeout == 0 ? RMT_WAIT_FOR_EVER : rmt_timeout)) {
          Serial.println("RMT :: nothing was read - returned after timeout");
        } else {
          Serial.println(String("RMT :: ") + String(rbuf_size) + " bytes were read!");
        }
    }
  }
  delay(3000);
  Serial.println();
  Serial.println("Next RMT reading attampt...");
  Serial.println();

#if 0 // testing workaround 
  // this also solves the issue once we reinit it in loop() and it enables RX Channel again 
  if (!rmtDeinit(rmtPin)) {
    Serial.println("Failed to deinit RMT.");
  }
#endif
}

```

## Related links
Fixes #12267

### CODE REVIEW

File: cores/esp32/esp32-hal-rmt.c [hunk 1]
```diff
@@ -401,6 +401,13 @@ static bool _rmtRead(int pin, rmt_data_t *data, size_t *num_rmt_symbols, bool wa
   xEventGroupClearBits(bus->rmt_events, RMT_FLAG_RX_DONE);
   bus->num_symbols_read = num_rmt_symbols;
 
+  if (waitForData) {
+    // must force stopping a previous reading first
+    rmt_disable(bus->rmt_channel_h);
+    // enable it again for reading a new data
+    rmt_enable(bus->rmt_channel_h);
```
Comment (SuGlider) [inline cores/esp32/esp32-hal-rmt.c]:
```suggestion
    // resets the reading channel to start fresh
    rmt_disable(bus->rmt_channel_h);
    rmt_enable(bus->rmt_channel_h);
```
