### PR TITLE
fix(zigbee): Fix RGB color calculation

### LINKED ISSUE #11619: [Bug] Color conversion in espXYToRgbColor() too dark – XYZ values scaled down by /100
The current implementation of espXYToRgbColor() divides the already-normalized XYZ values by 100.0f before the XYZ→sRGB matrix multiplication.
This scales X, Y, Z down by a factor 100 and therefore makes all RGB output ≈100× too dark.

```
// current code (snippet)
X = X / 100.0f;   // <-- should be removed
Y = Y / 100.0f;   // <-- should be removed
Z = Z / 100.0f;   // <-- should be removed
r = (X * 3.2406f) - (Y * 1.5372f) - (Z * 0.4986f);
...
```

https://github.com/espressif/arduino-esp32/blob/6015fd73e0d9d065c80fc79ef0f35d3273a217de/libraries/Zigbee/src/ep/ZigbeeColorDimmableLight.cpp#L86C24-L86C39

### PR DESCRIPTION
**Pull request by P-R-O-C-H-Y**
## Description of Change
This pull request introduces changes to improve color conversion functionality and refactors related code for clarity and flexibility. The most significant updates include adding an optional scaling parameter to the `espXYToRgbColor` function, modifying its usage across the codebase, and updating the header file to reflect these changes.

Before:
RED color on max level (100%) - RGB(68,0,0)

After fix:
RED color on max level (100%) - RGB(255,0,0)

## Tests scenarios
Tested using ColorDimmableLight example

## Related links
Closes #11619

### CODE REVIEW

File: cores/esp32/ColorFormat.h [hunk 1]
```diff
@@ -49,7 +50,7 @@ typedef struct HsvColor_t espHsvColor_t;
 typedef struct XyColor_t espXyColor_t;
 typedef struct CtColor_t espCtColor_t;
 
-espRgbColor_t espXYToRgbColor(uint8_t Level, uint16_t current_X, uint16_t current_Y);
+espRgbColor_t espXYToRgbColor(uint8_t Level, uint16_t current_X, uint16_t current_Y, bool addXYZScaling);
```
Comment (lucasssvaz) [inline cores/esp32/ColorFormat.h:53]: Just to avoid breaking changes:

```suggestion
espRgbColor_t espXYToRgbColor(uint8_t Level, uint16_t current_X, uint16_t current_Y, bool addXYZScaling = false);
```

Comment (P-R-O-C-H-Y) [reply cores/esp32/ColorFormat.h:53]: You can't do this in C, its a C++ feature.

Comment (lucasssvaz) [reply cores/esp32/ColorFormat.h:53]: You are right, my bad. Then we can do something like this:

```suggestion
espRgbColor_t espXYToRgbColor(uint8_t Level, uint16_t current_X, uint16_t current_Y, bool addXYZScaling);
espRgbColor_t espXYToRgbColor(uint8_t Level, uint16_t current_X, uint16_t current_Y);
```

And then do:

``` c
espXYToRgbColor(uint8_t Level, uint16_t current_X, uint16_t current_Y) {
    espXYToRgbColor(Level, current_X, current_Y, false);
}
```

Comment (P-R-O-C-H-Y) [reply cores/esp32/ColorFormat.h:53]: Also a C++ feature :D. Lets keep it like this

**Review by me-no-dev — APPROVED** [review]
