### PR TITLE
Fixes UART MODBUS and Loopback issue

### LINKED ISSUE #6126: UART Loopback doesn't work on 2.0.2
### Related Information
https://github.com/espressif/arduino-esp32/pull/5549#issuecomment-1009642889

### Board

ESP32, ESP32-S2 and ESP32-C3

### Hardware Configuration

ESP32 - loopback on UART2 : TX2 <--> RX2
ESP32-S2 and ESP32-C3 - loopback on UART1 : TX1 <--> RX1

### Description

When trying to send data in a UART loopback configuration, it fails and nothing is read.
Using Arduino Core 2.0.0 and 2.0.1 - it works fine. The issue is with v2.0.2
Most problably something related to last change on support to MODBUS https://github.com/espressif/arduino-esp32/pull/6026

### Sketch

```cpp
HardwareSerial LOOPBACK_UART(2);  // UART2 on ESP32 and UART1 on S2/C3

void setup() {
  Serial.begin(115200);
  LOOPBACK_UART.begin(115200);

  Serial.println("Serial Port 0 - Testing");
}


void loop() {
  static uint8_t count = 0;

  //Shorted Pins TX<->RX using ESP32/UART2 or S2/C3/UART1
  LOOPBACK_UART.write('0' + count);
  if (LOOPBACK_UART.available()) {
    Serial.write(LOOPBACK_UART.read());
  }
  count++;
  if ('0' + count > 'Z') {
    count = 0;
    LOOPBACK_UART.println();
  }
  delay(100);
}
```

### Debug Message

```plain
Correct Output should be:

ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1420
ho 0 tail 12 room 4
load:0x40078000,len:13540
load:0x40080400,len:3604
entry 0x400805f0
Serial Port 0 - Testing
0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ
```

but with v2.0.2 there is no output after the message  ```Serial Port 0 - Testing```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Summary
This PR fixes an issue created by #6026 not allowing UART loopback to work correctly.
It fixes both at the same time:
- makes flush() to wait up to the end of UART transmission before returning, fixing issue related to MODBUS #5877 
- solves the UART loopback issue in https://github.com/espressif/arduino-esp32/pull/5549#issuecomment-1009642889 and #6126

## Impact
None.

## Related links
Fixes #6126 
https://github.com/espressif/arduino-esp32/pull/5549#issuecomment-1009642889
#5877 
#4603

### CODE REVIEW

**Comment by TD-er** [comment]
Looks like a better approach.
Just waiting in the function that claims to actually just do that seems like a good idea :)

**Comment by mrengineer7777** [comment]
Much better solution. I approve.

File: cores/esp32/esp32-hal-uart.c [hunk 1]
```diff
@@ -306,7 +303,7 @@ void uartFlushTxOnly(uart_t* uart, bool txOnly)
     }
     
     UART_MUTEX_LOCK();
-    ESP_ERROR_CHECK(uart_wait_tx_done(uart->num, portMAX_DELAY));
+    while(!uart_ll_is_tx_idle(UART_LL_GET_HW(uart->num)));
```
Comment (avillacis) [inline cores/esp32/esp32-hal-uart.c:306]: Could somebody explain why exactly was the `uart_wait_tx_done()` call replaced here with the `uart_ll_is_tx_idle()` loop?

The ModbusMaster library is now broken in ESP32S2 v2.0.3, and it was working correctly in v2.0.2 (checked, I switch between the two versions at will). Our project, like many others, uses RS485 and flips the data-enable and read-enable pins, and uses flush() to wait until TX done before switching to RX mode. I still have to do more tests, but this change in particular seems the most likely culprit.

Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c:306]: @avillacis 

Have you read the issues related to this PR? They are related to MODBUS and `flush()` issues.

In summary:
`uart_wait_tx_done()` returns as soon as data is stored in TXRingBuffer, before the TX FIFO is really empty.

`uart_ll_is_tx_idle()` returns true just when TX FIFO is completely empty. 
The code for it is here - but it is the same for all other SoC, thus, the issue you see should happen for any ESP32-xx
https://github.com/espressif/esp-idf/blob/master/components/hal/esp32s2/include/hal/uart_ll.h#L714-L717

I tested `flush()` and I'm sure it works fine.
Maybe the issue you see isn't related to this PR.

Comment (avillacis) [reply cores/esp32/esp32-hal-uart.c:306]: Objection withdrawn. With access to the actual hardware, I found out that our RS485 card was echoing back request commands, and this echo was previously hidden by the `uart_set_mode()` call. Now I have manually added the call in our own code, and the issue was fixed.

However, is there any upstream bug report documenting this issue with `uart_wait_tx_done()`? Is it a true software bug, or a documentation error?

Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c:306]: Apparently `uart_wait_tx_done()` works correctly when used with `uart_set_mode(uart_num, UART_MODE_RS485_HALF_DUPLEX)`, considering an IDF environment.
 
But for Arduino, it isn't useful because of the its generic UART usage and APIs.
Thus we had to change it for the LL API.

Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c:306]: By default, IDF starts UART with  `uart_set_mode(uart_num, enumerator UART_MODE_UART)` and in this case, it returns as soon as data is stored in TXRingBuffer, before the TX FIFO is really empty.
