### PR TITLE
Touch change to init only selected GPIO.

### LINKED ISSUE #6443: touchRead T2 conflict with GPIO 27 but works fine in December release
### Board

ESP32 Dev Module

### Device Description

Standard 38pin 

### Hardware Configuration

Jumper between 27 and 39 to read

### Version

latest master

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

When pin 27 is set output and high it works normal but when T2 is read it floats

The same sketch works fine with December release

Output from old version 22/12/2021 `ESP32 Arduino 2.0.2 based on ESP-IDF 4.4-beta1` works fine 
```
22:12:14.849 -> pin 27 is high
22:12:15.833 -> Jumper pin 27 to 39 = 4095
22:12:16.864 -> Jumper pin 27 to 39 = 4095
22:12:17.837 -> Jumper pin 27 to 39 = 4095
22:12:18.868 -> Jumper pin 27 to 39 = 4095
22:12:19.846 -> Jumper pin 27 to 39 = 4095
22:12:19.846 -> T2 = 47
22:12:20.830 -> Jumper pin 27 to 39 = 4095
22:12:21.861 -> Jumper pin 27 to 39 = 4095
22:12:22.837 -> Jumper pin 27 to 39 = 4095
22:12:23.868 -> Jumper pin 27 to 39 = 4095
22:12:24.852 -> Jumper pin 27 to 39 = 4095
22:12:24.852 -> T2 = 79
22:12:25.838 -> Jumper pin 27 to 39 = 4095
22:12:26.869 -> Jumper pin 27 to 39 = 4095
22:12:27.853 -> Jumper pin 27 to 39 = 4095
22:12:28.837 -> Jumper pin 27 to 39 = 4095
22:12:29.868 -> Jumper pin 27 to 39 = 4095
```

### Sketch

```cpp
void setup() {
	Serial.begin(115200);
	delay(1000);
	pinMode(27, OUTPUT);
	digitalWrite(27, HIGH);
	Serial.println("pin 27 is high");
}

void loop() {

	static unsigned long every1second = millis();
	if (millis() - every1second >= 1000) { every1second = millis();
		Serial.print("Jumper pin 27 to 39 = ");
		Serial.println(analogRead(39));
	}

	static unsigned long every5seconds = millis();
	if (millis() - every5seconds >= 5000) { every5seconds = millis();
		Serial.print("T2 = ");
		Serial.println(touchRead(T2));
	}
}
```

### Debug Message

```plain
22:18:26.952 -> pin 27 is high
22:18:27.981 -> Jumper pin 27 to 39 = 4095
22:18:28.977 -> Jumper pin 27 to 39 = 4095
22:18:29.962 -> Jumper pin 27 to 39 = 4095
22:18:30.982 -> Jumper pin 27 to 39 = 4095
22:18:31.966 -> T2 = 77
22:18:32.235 -> Jumper pin 27 to 39 = 0
22:18:33.219 -> Jumper pin 27 to 39 = 0
22:18:34.256 -> Jumper pin 27 to 39 = 0
22:18:35.230 -> Jumper pin 27 to 39 = 0
22:18:36.251 -> Jumper pin 27 to 39 = 0
22:18:36.954 -> T2 = 77
22:18:37.235 -> Jumper pin 27 to 39 = 0
22:18:38.258 -> Jumper pin 27 to 39 = 0
22:18:39.242 -> Jumper pin 27 to 39 = 0
22:18:40.235 -> Jumper pin 27 to 39 = 0
22:18:41.219 -> Jumper pin 27 to 39 = 0
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by P-R-O-C-H-Y**
## Description of Change
After touch has been refactored to use ESP-IDF API, its initialising all channels for touch loosing previously setup pins for different purposes. 

The change is that the `touchRead()` and `touchAttachInterrupt()` will initialise touch sensor, but will configure only the pad selected. Other pins will remain as was.

## Tests scenarios
Sketch from issue #6443 tested on ESP32 and S2+S3 with different pins.

## Related links
Closes #6443

### CODE REVIEW

File: cores/esp32/esp32-hal-touch.c [hunk 1]
```diff
@@ -119,11 +119,6 @@ static void __touchInit()
     if (err != ESP_OK) {
         goto err;
     }
-    // Initial no Threshold and setup
-    for (int i = 0; i < SOC_TOUCH_SENSOR_NUM; i++) {
-        __touchInterruptHandlers[i].fn =  NULL;
```
Comment (me-no-dev) [inline cores/esp32/esp32-hal-touch.c:124]: maybe keep this portion to init the handlers?

File: cores/esp32/esp32-hal-touch.c [hunk 2]
```diff
@@ -148,18 +143,7 @@ static void __touchInit()
     // Touch Sensor Timer initiated
     touch_pad_set_fsm_mode(TOUCH_FSM_MODE_TIMER);  // returns ESP_OK
     touch_pad_fsm_start();                         // returns ESP_OK
-
-    // Initial no Threshold and setup - TOUCH0 is internal denoise channel
-    for (int i = 1; i < SOC_TOUCH_SENSOR_NUM; i++) {
-        __touchInterruptHandlers[i].fn =  NULL;
-        touch_pad_config(i);                       // returns ESP_OK
-    }
-    // keep ISR activated - it can run all together (ISR + touchRead())
```
Comment (me-no-dev) [inline cores/esp32/esp32-hal-touch.c:157]: is there any downside to init ISR here? Seems that you only needed to delete `touch_pad_config(i);` to resolve the issue.

Comment (me-no-dev) [reply cores/esp32/esp32-hal-touch.c:157]: ah ok.
