### PR TITLE
Fixes baudrate with CPU Freq < 80MHz

### LINKED ISSUE #6032: setCpuFrequencyMhz() changes Serial bauds if frequency<80Mhz
### Board

ESP32 Dev module

### Device Description

ESP32 Dev module alone

### Hardware Configuration

Nothing

### Version

v2.0.1

### IDE Name

Arduino IDE

### Operating System

Ubuntu 20.04

### Flash frequency

80Mhz

### PSRAM enabled

no

### Upload speed

921600

### Description

When setting CPU frequency below 80Mhz, the serial monitor is garbage until I change the baud rate...
I manage to solve the problem by setting the Serial.begin(bauds)  to : 80 / cpufreq * monitor_bauds
See sketch attached.

### Sketch

```cpp
uint32_t Freq = 0;
const int bauds = 115200;
int my_bauds;
int cpufreqs[6] = {240, 160, 80, 40, 20, 10};
int i = 0;

void setup() {
  Freq = getCpuFrequencyMhz();
  if (Freq < 80) {
    my_bauds = 80 / Freq * bauds;
  }
  else {
    my_bauds = bauds;
  }

  Serial.begin(my_bauds);        // Attention dépend de la frequence CPU si elle est <80Mhz 
  delay(500);
  //
  Freq = getCpuFrequencyMhz();
  Serial.print("CPU Freq = ");
  Serial.print(Freq);
  Serial.println(" MHz");
  Freq = getXtalFrequencyMhz();
  Serial.print("XTAL Freq = ");
  Serial.print(Freq);
  Serial.println(" MHz");
  Freq = getApbFrequency();
  Serial.print("APB Freq = ");
  Serial.print(Freq);
  Serial.println(" Hz");
}
void loop() {
  Serial.print("\nchange CPU freq to ");
  Serial.println(cpufreqs[i]);
  delay(1000);
  setCpuFrequencyMhz(cpufreqs[i]);
  Freq = getCpuFrequencyMhz();
  Serial.print("Send to serial with my_bauds = ");
  Serial.println(my_bauds);
  Serial.print("CPU Freq = ");
  Serial.print(Freq);
  Serial.println(" MHz");
  //  Change bauds rate ?

  if (Freq < 80) {
    my_bauds = 80 / Freq * bauds;
  }
  else {
    my_bauds = bauds;
  }
  Serial.end();
  delay(1000);
  Serial.begin(my_bauds);
  delay(1000);
  Serial.print("\nchange my_bauds to ");
  Serial.println(my_bauds);
  Serial.print("Serial set to ");
  Serial.println(my_bauds);
  Serial.print("CPU Freq = ");
  Serial.print(Freq);
  Serial.println(" MHz");
  Serial.print("my_bauds = ");
  Serial.println(my_bauds);

  delay(1000);
  i++;
  i = i % 6;
}
```

### Debug Message

```plain
No debug message, just monitor output set to 115200
CPU Freq = 240 MHz
XTAL Freq = 40 MHz
APB Freq = 80000000 Hz

change CPU freq to 240
Send to serial with my_bauds = 115200
CPU Freq = 240 MHz

change my_bauds to 115200
Serial set to 115200
CPU Freq = 240 MHz
my_bauds = 115200

change CPU freq to 160
Send to serial with my_bauds = 115200
CPU Freq = 160 MHz

change my_bauds to 115200
Serial set to 115200
CPU Freq = 160 MHz
my_bauds = 115200

change CPU freq to 80
Send to serial with my_bauds = 115200
CPU Freq = 80 MHz

change my_bauds to 115200
Serial set to 115200
CPU Freq = 80 MHz
my_bauds = 115200

change CPU freq to 40
f⸮⸮⸮`                 AND OTHER GARBAGE
change my_bauds to 230400
Serial set to 230400
CPU Freq = 40 MHz
my_bauds = 230400

change CPU freq to 20
f⸮⸮⸮`                 AND OTHER GARBAGE
change my_bauds to 460800
Serial set to 460800
CPU Freq = 20 MHz
my_bauds = 460800

change CPU freq to 10
f⸮⸮⸮`                 AND OTHER GARBAGE
change my_bauds to 921600
Serial set to 921600
CPU Freq = 10 MHz
my_bauds = 921600
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by SuGlider**
## Summary
This PR fixes an issue with UART when CPUFreq is lower than 80MHz (APB Freq)

## Impact
No impact beside the fix.

## Related links
Fix #6032

### CODE REVIEW

File: cores/esp32/esp32-hal-uart.c [hunk 1]
```diff
@@ -69,6 +69,19 @@ static uart_t _uart_bus_array[] = {
 
 #endif
 
+// solves issue https://github.com/espressif/arduino-esp32/issues/6032
+// baudrate must be multiplied when CPU Frequency is lower than APB 80MHz
+uint32_t _get_effective_baudrate(uint32_t baudrate) 
+{
+    uint32_t Freq = getCpuFrequencyMhz();
```
Comment (P-R-O-C-H-Y) [inline cores/esp32/esp32-hal-uart.c:76]: Maybe more clearer if you use `getApbFrequency()` which is related to UART.
But it will return frequency in Hz, not in MHz.

Comment (me-no-dev) [reply cores/esp32/esp32-hal-uart.c:76]: Agreed here :)

Comment (SuGlider) [reply cores/esp32/esp32-hal-uart.c]: Yes, it gets better and clear. DONE. Thanks.
