### PR TITLE
fix: silence multiple warnings pointed in issue #11917

### LINKED ISSUE #11917: Various Compiler Warnings in ESP32 Framework after enabling warning flags
### Board

Custom ESP32 board

### Device Description

n/a

### Hardware Configuration

n/a

### Version

latest stable Release (if not listed below)

### Type

Task

### IDE Name

VSCode

### Operating System

n/a

### Flash frequency

n/a

### PSRAM enabled

yes

### Upload speed

n/a

### Description

I've enabled extra compiler warnings in the my [ksIotFrameworkLib ](https://github.com/cziter15/ksIotFrameworkLib) project. After enabling these, a number of warnings appeared when building arduino-esp32. Enabling these flags can help catch potential bugs and improve code quality.

```
-Wunused-variable            # Warn about unused local variables
-Wunused-parameter           # Warn about unused function parameters
-Wunused-function            # Warn about unused static functions
-Wunused-but-set-variable    # Warn about variables set but never read
-Wsign-compare               # Warn about signed/unsigned comparisons
-Wtype-limits                # Warn about type limit comparisons
-Wmissing-field-initializers # Warn about missing field initializers
-Wuninitialized              # Warn about uninitialized variables
-Wmaybe-uninitialized        # Warn about potentially uninitialized variables
-Wformat                     # Warn about printf/scanf format issues
-Wreturn-type                # Warn about missing return statements
-Wswitch                     # Warn about missing switch cases
-Wparentheses                # Warn about ambiguous parentheses
-Wsequence-point             # Warn about undefined behavior
-Wstrict-aliasing            # Warn about strict aliasing violations
-Wextra                      # Enable additional warnings beyond -Wall
```

I don’t necessarily recommend enabling these flags directly in the Arduino-ESP32 framework, but they can at least help resolve the issues listed. There may be more similar cases, so some form of automation could be very helpful.

For example, an unused parameter warning can be suppressed in several ways:

```cpp
void myFunction(int x)
{
    (void)x; // Silence unused parameter warning
}
```

or

```cpp
void myFunction(int /*x*/)
{
    // x is unused
}
```

or in C++17 and later:

```cpp
void myFunction([[maybe_unused]] int x)
{
    // x is unused
}
```

#### Network
- **NetworkClient.cpp:510** – comparison of integer expressions of different signedness (`long unsigned int` vs `int`)
- **NetworkInterface.cpp:49** – unused parameter `arg`

#### Ethernet
- **ETH.cpp:55** – unused parameter `arg`
- **ETH.cpp:98** – unused parameter `event_data`
- **ETH.cpp:445** – unused parameter `ctx`
- **ETH.cpp:919** – unused parameter `bus_pointer`

#### WiFi
- **WiFiGeneric.cpp:70** – unused parameter `arg`

#### NetworkClientSecure / SSL
- **ssl_client.cpp:29** – unused parameters `function`, `line`
- **ssl_client.cpp:228** – comparison of integer expressions of different signedness (`int` vs `size_t`)

#### Update
- **Updater.cpp:130** – unused parameter `label`
- **Updater.cpp:283** – comparison of integer expressions of different signedness (`int` vs `unsigned int`)

#### ESPmDNS
- **ESPmDNS.cpp:287** – comparison of integer expressions of different signedness (`int` vs `size_t`)
- **ESPmDNS.cpp:368** – comparison of integer expressions of different signedness (`int` vs `size_t`)
- **ESPmDNS.cpp:384** – comparison of integer expressions of different signedness (`int` vs `size_t`)

#### Hash
- **PBKDF2_HMACBuilder.cpp:112** – unused parameters `stream`, `maxLen`

#### AsyncUDP
- **AsyncUDP.cpp:166** – unused parameter `pvParameters`
- **AsyncUDP.cpp:347** – unused parameter `rport`
- **AsyncUDP.cpp:773** – unused parameter `upcb`

#### DNSServer
- **DNSServer.cpp:136** – comparison of integer expressions of different signedness (`int` vs `size_t`)

#### LittleFS
- **LittleFS.cpp:46** – unused parameter `maxOpenFiles`

#### WebServer / Middleware
- **Middleware.h:17** – unused parameter `server` (multiple files: Middleware, AuthenticationMiddleware, CorsMiddleware, LoggingMiddleware, MiddlewareChain)
- **Parsing.cpp:192** – comparison of integer expressions of different signedness (`size_t` vs `int`)
- **Parsing.cpp:209** – comparison of integer expressions of different signedness (`size_t` vs `int`)
- **Parsing.cpp:379** – comparison of integer expressions of different signedness (`long unsigned int` vs `const long int`)
- **Parsing.cpp:398** – comparison of integer expressions of different signedness (`long unsigned int` vs `const long int`)
- **RequestHandlersImpl.h:73** – unused parameter `requestUri`
- **RequestHandlersImpl.h:97** – unused parameter `requestUri`
- **WebServer.cpp:145** – unused parameters `mode`, `params`
- **WebServer.cpp:616** – `NetworkClient::flush()` is deprecated; use `clear()` instead

### Sketch

```cpp
n/a
```

### Debug Message

```plain
n/a
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by cziter15**
*By completing this PR sufficiently, you help us to review this Pull Request quicker and also help improve the quality of Release Notes*

### Checklist
1. [x] Please provide specific title of the PR describing the change, including the component name (*eg. „Update of Documentation link on Readme.md“*)
2. [x] Please provide related links (*eg. Issue which will be closed by this Pull Request*)
3. [x] Please **update relevant Documentation** if applicable
4. [x] Please check [Contributing guide](https://docs.espressif.com/projects/arduino-esp32/en/latest/contributing.html)
5. [x] Please **confirm option to "Allow edits and access to secrets by maintainers"** when opening a Pull Request

*This entire section above can be deleted if all items are checked.*

-----------
## Description of Change
Resolve warnings as described in #11917

## Related links
Closes #11917

### CODE REVIEW

**Comment by cziter15** [comment]
@me-no-dev Not sure about that `bus_pointer` check in ETH. Am I correct here?
PS. Is it mandatory to follow conventional commits inside a PR (not only PR title?) ?

File: libraries/WebServer/src/WebServer.cpp [hunk 1]
```diff
@@ -613,7 +615,7 @@ void WebServer::chunkResponseEnd() {
     log_e("Failed to write terminating chunk");
   }
 
-  _chunkedClient.flush();
+  _chunkedClient.clear();
```
Comment (Jason2866) [inline libraries/WebServer/src/WebServer.cpp]: This is a breaking change. Please revert.

Comment (cziter15) [reply libraries/WebServer/src/WebServer.cpp]: It's what warning suggested. Actually i'm on mobile, so limited ability to go through client classes. Why is it breaking?

Comment (Jason2866) [reply libraries/WebServer/src/WebServer.cpp]: makes no sense when beeing on mobile. Look through the PRs made regarding flush <-> clear

Comment (lucasssvaz) [reply libraries/WebServer/src/WebServer.cpp]: https://docs.espressif.com/projects/arduino-esp32/en/latest/migration_guides/2.x_to_3.0.html#id15

Comment (cziter15) [reply libraries/WebServer/src/WebServer.cpp]: It seems that the documentation isn’t accurate.

`flush()` is calling `clear()` at:

https://github.com/espressif/arduino-esp32/blob/b20655a009008e374fd37f5a6c45f3ba53b9ba86/libraries/Network/src/NetworkUdp.cpp#L293

https://github.com/espressif/arduino-esp32/blob/b20655a009008e374fd37f5a6c45f3ba53b9ba86/libraries/Network/src/NetworkClient.cpp#L382

but only in `WifiClientSecure.cpp` is actually doing nothing:
https://github.com/espressif/arduino-esp32/blob/b20655a009008e374fd37f5a6c45f3ba53b9ba86/libraries/NetworkClientSecure/src/NetworkClientSecure.h#L66

so yes @Jason2866 it's better not touch this, but that depecation is misleading

**Comment by me-no-dev** [comment]
@lucasssvaz PTAL

**Review by lucasssvaz — APPROVED** [review]

**Comment by cziter15** [comment]
Thank you 🎉
