### PR TITLE
fix(ble): readValue memory leak bug for multiple reads

### LINKED ISSUE #12446: Memory leak in BLE library(nimble based) BLERemoteCharacteristic::readValue() implementation
### Board

Any board using BLE library (nimble based)

### Device Description

It is two plain xiao esp32 s3. 

### Hardware Configuration

An external antennae required for xiao esp32 s3 boards

### Version

v3.3.7

### Type

Bug

### IDE Name

Arduino IDE

### Operating System

Not OS dependent

### Flash frequency

80 MHz

### PSRAM enabled

yes

### Upload speed

921600

### Description

I have a BLEServer (nimble based) with a characteristic with read property. My BLEClient (nimble based) connects to the server and read the characteristic multiple times every 1 second.
I observe a constant memory leak of 24 bytes using xPortGetFreeHeapSize() command for every call by BLERemoteCharacteristic::readUInt16() 

### Sketch

```cpp
// Client.ino

#include <BLEDevice.h>

#ifndef CONFIG_NIMBLE_ENABLED
#error "NIMBLE not enabled"
#endif

BLEUUID serviceUUID("5cf40769-85ff-4049-b458-20332e6acb70");
BLEUUID charUUID("8907bc98-0911-4c55-a418-cade296ca131");

BLEScan* pBLEScan = nullptr;
BLEClient* pClient = nullptr;
BLERemoteService* pRemoteService = nullptr;
BLERemoteCharacteristic* pRemoteCharacteristic = nullptr;
BLEAddress myDeviceAddress;
int advType;

class MyAdvertisedDeviceCallbacks : public BLEAdvertisedDeviceCallbacks {
  void onResult(BLEAdvertisedDevice advertisedDevice) {
    if(advertisedDevice.haveName()){
      if(advertisedDevice.getName() == "TestDevice"){
        myDeviceAddress = advertisedDevice.getAddress();
        advType = advertisedDevice.getAddressType();
        pBLEScan->stop();
      }
    }
  }
};

void setup() {
  Serial.begin(115200);
  delay(1000);
  BLEDevice::init();
  pBLEScan = BLEDevice::getScan();

  // One time scan to get mac address of my test advertising device
  pBLEScan->setActiveScan(false);
  pBLEScan->setAdvertisedDeviceCallbacks(new MyAdvertisedDeviceCallbacks());
  pBLEScan->start(0,false);
  pBLEScan->clearResults();

  pClient = BLEDevice::createClient();
  if(!pClient) return;

  pClient->connect(myDeviceAddress,advType);
  if(!pClient->isConnected()) return;

  pRemoteService = pClient->getService(serviceUUID);
  if(!pRemoteService) return;

  pRemoteCharacteristic = pRemoteService->getCharacteristic(charUUID);
  if(!pRemoteCharacteristic) return;

  if(!pRemoteCharacteristic->canRead()) return;
  
  for(int i=0;i<5;i++){
    // String readVal = pRemoteCharacteristic->readValue();
    int readVal = pRemoteCharacteristic->readUInt16();
    // Serial.printf("val: %s,length: %d, free heap space: %lu\n",readVal,readVal.length(),xPortGetFreeHeapSize());
    Serial.printf("val: %d, free heap space: %lu\n",readVal,xPortGetFreeHeapSize());
    delay(1000); 
  }

  pClient->disconnect();

  while(!pClient->isConnected()) delay(1000);


}

void loop() {
  delay(10000);
}

// Server.ino
#include <BLEDevice.h>

BLEUUID serviceUUID("5cf40769-85ff-4049-b458-20332e6acb70");
BLEUUID charUUID("8907bc98-0911-4c55-a418-cade296ca131");

BLEServer* pServer=nullptr;
BLEService* pService=nullptr;
BLECharacteristic* pCharacteristic = nullptr;
BLEAdvertising* pAdvertising = nullptr;

const uint16_t value = 244;

void setup() {
  Serial.begin(115200);

  BLEDevice::init("TestDevice");
  pServer = BLEDevice::createServer();
  pService = pServer->createService(serviceUUID);
  pCharacteristic = pService->createCharacteristic(charUUID,BLECharacteristic::PROPERTY_READ);
  pCharacteristic->setValue(value);
  pService->start();

  pAdvertising = BLEDevice::getAdvertising();
  pAdvertising->setName("TestDevice");  
  pAdvertising->start(0); 
}

void loop() {
  // put your main code here, to run repeatedly:
  delay(1000);
}
```

### Debug Message

```plain
None
```

### Other Steps to Reproduce

_No response_

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [x] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by desaikaran1976**
Fixes #12446
Problem:
If readValue() is done only once per pClient existence or if services are cleared then there is no issue. If readValue() is done multiple times previous m_rawData pointer is lost leading to memory leak.
Solution:
Before assigning new memory for the next readValue() or readUInt16() if m_rawData is freed if not nullptr.
Used code suggested in #12446 using xiao esp32 s3

### CODE REVIEW

File: libraries/BLE/src/BLERemoteCharacteristic.cpp [hunk 1]
```diff
@@ -938,6 +938,7 @@ String BLERemoteCharacteristic::readValue() {
 
   m_semaphoreReadCharEvt.take("readValue");
   m_value = value;
+  if(m_rawData) free(m_rawData);
```
Comment (lucasssvaz) [inline libraries/BLE/src/BLERemoteCharacteristic.cpp]: No need for the `if`

```suggestion
  free(m_rawData);
```
