### PR TITLE
fix(zigbee): Fix rejoin issue for battery powered devices

### LINKED ISSUE #10612: Zigbee: problem with battery powered devices after power off/on
### Board

ESP32C6

### Device Description

DevKit

### Hardware Configuration

No external connections, only modul. 

### Version

latest development Release Candidate (RC-X)

### IDE Name

Arduino IDE

### Operating System

Windows 11

### Flash frequency

80MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

Using Zigbee2MQTT battery powered device will be recognized and values will be reported as expected.
After power on/off device (remove power) the device will not more join and send values to the network and reboots regularly.

Have seen that this is happen only for battery powered devices.

If adding some delay after `Zigbee.addEndpoint(&zbTempSensor);` and after `Zigbee.begin();` device will not reboot, but will also not join again / report values (some other debug messages).

### Sketch

```cpp
example Zigbee_Temperature_Sensor.ino modified:

static void temp_sensor_value_update(void *arg) {
  for (;;) {
    // Read temperature sensor value
    float tsens_value = temperatureRead();
    log_v("Temperature sensor value: %.2f°C", tsens_value);
    // Update temperature value in Temperature sensor EP
    zbTempSensor.setTemperature(tsens_value);
    zbTempSensor.setHumidity(tsens_value);
    delay(1000);
  }
}

....
  // Optional: set Zigbee device name and model
  zbTempSensor.setManufacturerAndModel("Espressif", "ZigbeeTempSensor");

  zbTempSensor.setPowerSource(ZB_POWER_SOURCE_BATTERY, 100);
  zbTempSensor.addHumiditySensor(0, 100, 1);

  // Set minimum and maximum temperature measurement value (10-50°C is default range for chip temperature measurement)
  zbTempSensor.setMinMaxValue(10, 50);
....
```

### Debug Message

```plain
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-C6
  Package           : 1
  Revision          : 0.01
  Cores             : 1
  CPU Frequency     : 160 MHz
  XTAL Frequency    : 40 MHz
  Features Bitfield : 0x00000052
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : Yes
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   445324 B ( 434.9 KB)
  Free Bytes        :   414112 B ( 404.4 KB)
  Allocated Bytes   :    24260 B (  23.7 KB)
  Minimum Free Bytes:   409300 B ( 399.7 KB)
  Largest Free Block:   376820 B ( 368.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         :  4194304 B (4 MB)
  Block Size        :    65536 B (  64.0 KB)
  Sector Size       :     4096 B (   4.0 KB)
  Page Size         :      256 B (   0.2 KB)
  Bus Speed         : 40 MHz
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1388.0 KB, type: DATA, subtype: SPIFFS
         zb_storage : addr: 0x003EB000, size:    16.0 KB, type: DATA, subtype: FAT
             zb_fct : addr: 0x003EF000, size:     4.0 KB, type: DATA, subtype: FAT
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Nov 16 2024 21:10:20
  Compile Host OS   : windows
  ESP-IDF Version   : v5.3.1-638-ga0f798cfc4-dirty
  Arduino Version   : 3.1.0
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32C6_DEV
  Arduino Variant   : esp32c6
  Arduino FQBN      : esp32:esp32:esp32c6:UploadSpeed=921600,CDCOnBoot=cdc,CPUFreq=160,FlashFreq=80,FlashMode=qio,FlashSize=4M,PartitionScheme=zigbee,DebugLevel=verbose,EraseFlash=all,JTAGAdapter=default,ZigbeeMode=ed
============ Before Setup End ============
[   990][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 12 already has type USB_DM (38) with bus 0x4081155c
[   991][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 13 already has type USB_DP (39) with bus 0x4081155c
[   991][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type GPIO (1) successfully set to 0x4200348e
[   992][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 9 successfully set to type GPIO (1) with bus 0xa
[   993][D][ZigbeeCore.cpp:66] addEndpoint(): Endpoint: 10, Device ID: 0x0302
[   993][D][ZigbeeCore.cpp:103] zigbeeInit(): Initialize Zigbee stack
[  1028][D][ZigbeeCore.cpp:110] zigbeeInit(): Register all Zigbee EPs in list
[  1030][I][ZigbeeCore.cpp:118] zigbeeInit(): List of registered Zigbee EPs:
[  1030][I][ZigbeeCore.cpp:120] zigbeeInit(): Device type: Temperature Sensor, Endpoint: 10, Device ID: 0x0302
Zigbee stack assertion failed common/zb_error_indication.c:8
abort() was called at PC 0x42012b5d on core 0
Core  0 register dump:
MEPC    : 0x40801588  RA      : 0x40807ffc  SP      : 0x40824220  GP      : 0x4080f824
TP      : 0x408243b0  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x4082424c  S1      : 0x4082424c  A0      : 0x40824258  A1      : 0x4082423a
A2      : 0x00000000  A3      : 0x40824285  A4      : 0x00000001  A5      : 0x40816000
A6      : 0x00000000  A7      : 0x76757473  S2      : 0x00000000  S3      : 0x4081365c
S4      : 0x00000001  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
MHARTID : 0x00000000

Stack memory:
40824220: 0x00000000 0x00000000 0x40824238 0x4080dea6 0x00000000 0x00000000 0x00000030 0x40810e00
40824240: 0x4082424c 0x40810e1c 0x40824238 0x31303234 0x64356232 0x00000000 0x726f6261 0x20292874
40824260: 0x20736177 0x6c6c6163 0x61206465 0x43502074 0x34783020 0x32313032 0x20643562 0x63206e6f
40824280: 0x2065726f 0x00000030 0x00000000 0x5c9fa1b1 0x0000002f 0x40813a48 0x42075e69 0x42012b60
408242a0: 0x00000bd6 0x00000000 0x00000000 0x00000051 0x00000000 0x00000000 0x000000fe 0x420374f8
408242c0: 0x00000000 0x40813a48 0x40824320 0x42013ed6 0x00000000 0x00000000 0x00000ac0 0x0000001f
408242e0: 0x00000019 0x001f0040 0x00000000 0x00000000 0x000f0002 0x00000000 0x00000000 0x00000000
40824300: 0x0000001f 0x00000010 0x40813a48 0x420159e6 0x00000000 0x00000000 0x00000000 0x00000000
40824320: 0x00000019 0x001f0040 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x4202bd84
40824340: 0x00000000 0x00000000 0x00000000 0x4202c10e 0x00000000 0x00000000 0x00000000 0x42009084
40824360: 0x00000000 0x00000000 0x00000000 0x4200090c 0x00000000 0x00000000 0x00000000 0x408092b8
40824380: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
408243a0: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xbaad5678 0x00058251 0x408169c4
408243c0: 0x408169c4 0xfc031e0c 0x78849b34 0x30c832a9 0x9d9c5b2a 0xae36ed22 0xadd31283 0xecb1fcf5
408243e0: 0x7c32a028 0x2d446289 0xe2cffffd 0x711286e4 0xe66f0bce 0x82719d97 0x7645118a 0x130cd72f
40824400: 0x8c12a31c 0x7158b14d 0x8a3fb378 0x9e867233 0x66837636 0xe997fc45 0x330036ca 0x0a0a8952
40824420: 0xc024d6f7 0xff7c0bb3 0xfb6f2de7 0x378053c9 0xec565c7f 0x7e9c383f 0xaad1000d 0x04923695
40824440: 0xeb226082 0xd2808128 0x384ef7ae 0xfd399651 0x2d15af93 0x244ab39b 0xa0f9c680 0x436558df
40824460: 0x053a2b45 0xf23ac453 0xba7fb0b1 0xf068200a 0x4539f116 0x1712f8c7 0x0666cf28 0x7344999c
40824480: 0xd9cd50c1 0xd032329a 0x963c700b 0x167d9b9d 0x39809846 0x53548e10 0x8a1a132c 0x793164ac
408244a0: 0x06065915 0x0109a3a0 0xe565e7e9 0x8d7fffef 0x5fcf1039 0xd80dcd7d 0xa1228c21 0x0b311ccc
408244c0: 0xd8709c0d 0x2cec1457 0xb87cd0f7 0x5b756ef5 0xd98cefbe 0xffff653f 0x891a1046 0x1a8284e1
408244e0: 0x4037cdc3 0x31c19682 0x2dbe8ffd 0x294cb0b3 0xb6e1bcf5 0x4afe2c80 0xc19ca484 0x6000aba2
40824500: 0xb43bd81c 0x407e7d43 0x1deca8ae 0xa89a607b 0x74976fa9 0xaa3bfa1a 0x0b9000b4 0x14a83808
40824520: 0x830eb325 0x092140d5 0xdbe5cddf 0xba4fd1ad 0xeef9a462 0x7e268f92 0x94995434 0x2cbaa2dc
40824540: 0xbe382aa4 0xaaa71779 0x6c1dd7f3 0xf5a629c4 0xfeedbf7e 0xf7f6df1f 0x281e284a 0x5f147465
40824560: 0x51c3c99c 0x16b20c02 0x233a567e 0x5d493983 0xd11ef234 0xf7fc57bb 0xcec44ee9 0x8024372a
40824580: 0x02410490 0x41922360 0xe2e2ecfd 0x0543feb7 0xda2039e6 0xfa72cff9 0xd6d01951 0x2c4b020d
408245a0: 0x0081cb07 0x05140fa4 0xfed2fd8b 0xe73f7a6f 0xe7dbf128 0xe6dc0622 0x4c651164 0x627c4962
408245c0: 0xd82de23e 0x246307be 0x8178f7f9 0xc137f57b 0x8ff857ec 0x435fefe0 0x3a0791b7 0x51f6b636
408245e0: 0x26cd3c8b 0x2ee16160 0x51e99b82 0x38b9a5b0 0xfecfa861 0xfb2567bd 0x1490ee9f 0x2d76ef80
40824600: 0x0a64f0e1 0x3b290665 0xcdf33fa8 0xf9ed4e27 0xbd850fbf 0x00762f2e 0x0849ca10 0xcd048484



ELF file SHA256: 5542d8f16

Rebooting...
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0xc (SW_CPU),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x4001975a
SPIWP:0xee
mode:DIO, clock div:2
load:0x40875720,len:0x1190
load:0x4086c110,len:0xd98
load:0x4086e610,len:0x2e84
entry 0x4086c110
[     0][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RX (2) successfully set to 0x42005dce
[    12][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_TX (3) successfully set to 0x42005d92
[    23][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_CTS (4) successfully set to 0x42005d56
[    34][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RTS (5) successfully set to 0x42005d1a
[    46][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RX (2) successfully set to 0x42005dce
[    57][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_TX (3) successfully set to 0x42005d92
[    68][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_CTS (4) successfully set to 0x42005d56
[    80][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RTS (5) successfully set to 0x42005d1a
[    91][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type USB_DM (38) successfully set to 0x420025c0
[   102][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type USB_DP (39) successfully set to 0x420025c0
[   114][V][ZigbeeEP.cpp:18] ZigbeeEP(): Endpoint: 10
[   131][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 17 successfully set to type UART_RX (2) with bus 0x4080f0fc
[   141][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 16 successfully set to type UART_TX (3) with bus 0x4080f0fc
[   152][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 12 successfully set to type USB_DM (38) with bus 0x4081155c
[   163][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 13 successfully set to type USB_DP (39) with bus 0x4081155c
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-C6
  Package           : 1
  Revision          : 0.01
  Cores             : 1
  CPU Frequency     : 160 MHz
  XTAL Frequency    : 40 MHz
  Features Bitfield : 0x00000052
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : Yes
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   445324 B ( 434.9 KB)
  Free Bytes        :   409124 B ( 399.5 KB)
  Allocated Bytes   :    29216 B (  28.5 KB)
  Minimum Free Bytes:   409124 B ( 399.5 KB)
  Largest Free Block:   376820 B ( 368.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         :  4194304 B (4 MB)
  Block Size        :    65536 B (  64.0 KB)
  Sector Size       :     4096 B (   4.0 KB)
  Page Size         :      256 B (   0.2 KB)
  Bus Speed         : 40 MHz
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1388.0 KB, type: DATA, subtype: SPIFFS
         zb_storage : addr: 0x003EB000, size:    16.0 KB, type: DATA, subtype: FAT
             zb_fct : addr: 0x003EF000, size:     4.0 KB, type: DATA, subtype: FAT
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Nov 16 2024 21:10:20
  Compile Host OS   : windows
  ESP-IDF Version   : v5.3.1-638-ga0f798cfc4-dirty
  Arduino Version   : 3.1.0
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32C6_DEV
  Arduino Variant   : esp32c6
  Arduino FQBN      : esp32:esp32:esp32c6:UploadSpeed=921600,CDCOnBoot=cdc,CPUFreq=160,FlashFreq=80,FlashMode=qio,FlashSize=4M,PartitionScheme=zigbee,DebugLevel=verbose,EraseFlash=all,JTAGAdapter=default,ZigbeeMode=ed
============ Before Setup End ============
[   286][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 12 already has type USB_DM (38) with bus 0x4081155c
[   287][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 13 already has type USB_DP (39) with bus 0x4081155c
[   287][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type GPIO (1) successfully set to 0x4200348e
[   288][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 9 successfully set to type GPIO (1) with bus 0xa
[   289][D][ZigbeeCore.cpp:66] addEndpoint(): Endpoint: 10, Device ID: 0x0302
[   289][D][ZigbeeCore.cpp:103] zigbeeInit(): Initialize Zigbee stack
[   325][D][ZigbeeCore.cpp:110] zigbeeInit(): Register all Zigbee EPs in list
[   326][I][ZigbeeCore.cpp:118] zigbeeInit(): List of registered Zigbee EPs:
[   327][I][ZigbeeCore.cpp:120] zigbeeInit(): Device type: Temperature Sensor, Endpoint: 10, Device ID: 0x0302
[   424][V][ZigbeeCore.cpp:301] esp_zb_app_signal_handler(): ZDO signal: ZDO Config Ready (0x17), status: ESP_FAIL
[   425][I][ZigbeeCore.cpp:191] esp_zb_app_signal_handler(): Zigbee stack initialized
[  1336][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 24.00°C
[  1336][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  1337][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2400
[  1337][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  1338][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2400
=========== After Setup Start ============
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   445324 B ( 434.9 KB)
  Free Bytes        :   384116 B ( 375.1 KB)
  Allocated Bytes   :    53280 B (  52.0 KB)
  Minimum Free Bytes:   383988 B ( 375.0 KB)
  Largest Free Block:   352244 B ( 344.0 KB)
------------------------------------------
GPIO Info:
------------------------------------------
  GPIO : BUS_TYPE[bus/unit][chan]
  --------------------------------------
     9 : GPIO
    12 : USB_DM
    13 : USB_DP
    16 : UART_TX[0]
    17 : UART_RX[0]
============ After Setup End =============
[  2338][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 25.00°C
[  2339][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  2339][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2500
[  2340][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  2340][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2500
[  3340][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 26.00°C
[  3341][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  3341][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2600
[  3342][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  3342][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2600
[  4342][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 26.00°C
[  4343][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  4343][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2600
[  4343][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  4344][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2600
[  5344][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 27.00°C
[  5345][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  5345][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2700
[  5346][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  5346][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2700
[  6346][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 27.00°C
[  6347][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  6347][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2700
[  6348][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  6348][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2700
[  7348][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 28.00°C
[  7349][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  7349][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2800
[  7350][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  7350][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2800
[  8350][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 28.00°C
[  8351][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  8351][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2800
[  8352][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  8352][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2800
[  9352][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 28.00°C
[  9353][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[  9353][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2800
[  9354][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[  9354][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2800
[ 10354][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 29.00°C
[ 10355][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[ 10355][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2900
[ 10356][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[ 10356][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2900
[ 11356][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 29.00°C
[ 11357][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[ 11357][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2900
[ 11358][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[ 11358][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2900
[ 12358][V][Zigbee_Temperature_Sensor.ino:45] temp_sensor_value_update(): Temperature sensor value: 29.00°C
[ 12359][V][ZigbeeTempSensor.cpp:68] setTemperature(): Updating temperature sensor value...
[ 12359][D][ZigbeeTempSensor.cpp:70] setTemperature(): Setting temperature to 2900
[ 12360][V][ZigbeeTempSensor.cpp:107] setHumidity(): Updating humidity sensor value...
[ 12360][D][ZigbeeTempSensor.cpp:109] setHumidity(): Setting humidity to 2900
[ 12772ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0xc (SW_CPU),boot:0xc (SPI_FAST_FLASH_BOOT)
Saved PC:0x4001975a
SPIWP:0xee
mode:DIO, clock div:2
load:0x40875720,len:0x1190
load:0x4086c110,len:0xd98
load:0x4086e610,len:0x2e84
entry 0x4086c110
[     0][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RX (2) successfully set to 0x42005dce
[    12][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_TX (3) successfully set to 0x42005d92
[    23][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_CTS (4) successfully set to 0x42005d56
[    34][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RTS (5) successfully set to 0x42005d1a
[    46][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RX (2) successfully set to 0x42005dce
[    57][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_TX (3) successfully set to 0x42005d92
[    68][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_CTS (4) successfully set to 0x42005d56
[    80][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type UART_RTS (5) successfully set to 0x42005d1a
[    91][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type USB_DM (38) successfully set to 0x420025c0
[   102][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type USB_DP (39) successfully set to 0x420025c0
[   114][V][ZigbeeEP.cpp:18] ZigbeeEP(): Endpoint: 10
[   131][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 17 successfully set to type UART_RX (2) with bus 0x4080f0fc
[   141][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 16 successfully set to type UART_TX (3) with bus 0x4080f0fc
[   152][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 12 successfully set to type USB_DM (38) with bus 0x4081155c
[   163][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 13 successfully set to type USB_DP (39) with bus 0x4081155c
=========== Before Setup Start ===========
Chip Info:
------------------------------------------
  Model             : ESP32-C6
  Package           : 1
  Revision          : 0.01
  Cores             : 1
  CPU Frequency     : 160 MHz
  XTAL Frequency    : 40 MHz
  Features Bitfield : 0x00000052
  Embedded Flash    : No
  Embedded PSRAM    : No
  2.4GHz WiFi       : Yes
  Classic BT        : No
  BT Low Energy     : Yes
  IEEE 802.15.4     : Yes
------------------------------------------
INTERNAL Memory Info:
------------------------------------------
  Total Size        :   445324 B ( 434.9 KB)
  Free Bytes        :   409124 B ( 399.5 KB)
  Allocated Bytes   :    29216 B (  28.5 KB)
  Minimum Free Bytes:   409124 B ( 399.5 KB)
  Largest Free Block:   376820 B ( 368.0 KB)
------------------------------------------
Flash Info:
------------------------------------------
  Chip Size         :  4194304 B (4 MB)
  Block Size        :    65536 B (  64.0 KB)
  Sector Size       :     4096 B (   4.0 KB)
  Page Size         :      256 B (   0.2 KB)
  Bus Speed         : 40 MHz
  Bus Mode          : QIO
------------------------------------------
Partitions Info:
------------------------------------------
                nvs : addr: 0x00009000, size:    20.0 KB, type: DATA, subtype: NVS
            otadata : addr: 0x0000E000, size:     8.0 KB, type: DATA, subtype: OTA
               app0 : addr: 0x00010000, size:  1280.0 KB, type:  APP, subtype: OTA_0
               app1 : addr: 0x00150000, size:  1280.0 KB, type:  APP, subtype: OTA_1
             spiffs : addr: 0x00290000, size:  1388.0 KB, type: DATA, subtype: SPIFFS
         zb_storage : addr: 0x003EB000, size:    16.0 KB, type: DATA, subtype: FAT
             zb_fct : addr: 0x003EF000, size:     4.0 KB, type: DATA, subtype: FAT
           coredump : addr: 0x003F0000, size:    64.0 KB, type: DATA, subtype: COREDUMP
------------------------------------------
Software Info:
------------------------------------------
  Compile Date/Time : Nov 16 2024 21:10:20
  Compile Host OS   : windows
  ESP-IDF Version   : v5.3.1-638-ga0f798cfc4-dirty
  Arduino Version   : 3.1.0
------------------------------------------
Board Info:
------------------------------------------
  Arduino Board     : ESP32C6_DEV
  Arduino Variant   : esp32c6
  Arduino FQBN      : esp32:esp32:esp32c6:UploadSpeed=921600,CDCOnBoot=cdc,CPUFreq=160,FlashFreq=80,FlashMode=qio,FlashSize=4M,PartitionScheme=zigbee,DebugLevel=verbose,EraseFlash=all,JTAGAdapter=default,ZigbeeMode=ed
============ Before Setup End ============
[   286][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 12 already has type USB_DM (38) with bus 0x4081155c
[   287][I][esp32-hal-periman.c:141] perimanSetPinBus(): Pin 13 already has type USB_DP (39) with bus 0x4081155c
[   287][V][esp32-hal-periman.c:235] perimanSetBusDeinit(): Deinit function for type GPIO (1) successfully set to 0x4200348e
[   288][V][esp32-hal-periman.c:160] perimanSetPinBus(): Pin 9 successfully set to type GPIO (1) with bus 0xa
[   289][D][ZigbeeCore.cpp:66] addEndpoint(): Endpoint: 10, Device ID: 0x0302
[   289][D][ZigbeeCore.cpp:103] zigbeeInit(): Initialize Zigbee stack
[   337][D][ZigbeeCore.cpp:110] zigbeeInit(): Register all Zigbee EPs in list
[   339][I][ZigbeeCore.cpp:118] zigbeeInit(): List of registered Zigbee EPs:
[   339][I][ZigbeeCore.cpp:120] zigbeeInit(): Device type: Temperature Sensor, Endpoint: 10, Device ID: 0x0302
Zigbee stack assertion failed common/
abort() was called at PC 0x42012b5d on core 0
Core  0 register dump:
MEPC    : 0x40801588  RA      : 0x40807ffc  SP      : 0x40824490  GP      : 0x4080f824
TP      : 0x40824620  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130
S0/FP   : 0x408244bc  S1      : 0x408244bc  A0      : 0x408244c8  A1      : 0x408244aa
A2      : 0x00000000  A3      : 0x408244f5  A4      : 0x00000001  A5      : 0x40816000
A6      : 0x00000000  A7      : 0x76757473  S2      : 0x00000000  S3      : 0x40813658
S4      : 0x00000002  S5      : 0x00000000  S6      : 0x00000000  S7      : 0x00000000
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000000
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000
MHARTID : 0x00000000

Stack memory:
40824490: 0x00000000 0x00000000 0x408244a8 0x4080dea6 0x00000000 0x00000000 0x00000030 0x40810e00
408244b0: 0x408244bc 0x40810e1c 0x408244a8 0x31303234 0x64356232 0x00000000 0x726f6261 0x20292874
408244d0: 0x20736177 0x6c6c6163 0x61206465 0x43502074 0x34783020 0x32313032 0x20643562 0x63206e6f
408244f0: 0x2065726f 0x00000030 0x00000000 0x7bf1811f 0x0000002f 0x40813a48 0x42075e69 0x42012b60
40824510: 0x0000cbb3 0x00000000 0x00000000 0x00000051 0x00000000 0x00000000 0x000000fe 0x420374f8
40824530: 0x00000000 0x40813a48 0x40824590 0x42013ed6 0x00000000 0x00000000 0x00000840 0x0001001f
40824550: 0x00000026 0x001f0040 0x00000000 0x00000000 0x00160003 0x00000002 0x00000000 0x00000000
40824570: 0x0000001f 0x00000010 0x40813a48 0x420159e6 0x00000000 0x00000000 0x00000000 0x00000000
40824590: 0x00000026 0x001f0040 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x4202bd84
408245b0: 0x00000000 0x00000000 0x00000000 0x4202c10e 0x00000000 0x00000000 0x00000000 0x42009084
408245d0: 0x00000000 0x00000000 0x00000000 0x4200090c 0x00000000 0x00000000 0x00000000 0x408092b8
408245f0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
40824610: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xbaad5678
40824630: 0x00057fd9 0x408169c4 0x408169c4 0x00000000 0x00000000 0x00000000 0xffffffff 0x7fefffff
40824650: 0x00000000 0x3fe00000 0x403d0000 0x00000000 0x00000000 0x3fc00000 0x00000000 0x40300000
40824670: 0x00000000 0x4004e20c 0x00000000 0x00000000 0x00000000 0x00000000 0xffffffff 0x40824b18
40824690: 0x00000000 0x3fe00000 0x00000000 0xa5a5a5a5 0x00000005 0x00000000 0x00000000 0x40300000
408246b0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x408246cc 0x00000000 0x00000000 0x42071778
408246d0: 0x00000002 0x4082476c 0x00000004 0x4082476b 0x00000005 0x00000000 0x00000002 0x00000000
408246f0: 0xa5a5a5a5 0xa5a5a5a5 0x4081999c 0xa5a5a5a5 0x4082470c 0x00000000 0x00000000 0x420701fc
40824710: 0x00000005 0x40819998 0x00000002 0x4004e20c 0x00000001 0x4081999a 0x00000002 0xa5a5a5a5
40824730: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
40824750: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x31a5a5a5 0x30303932
40824770: 0xffffffff 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
40824790: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x31a5a5a5 0x35343332
408247b0: 0xffffffff 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
408247d0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
408247f0: 0x00003048 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x42071627 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
40824810: 0x0000006d 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x42071704 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
40824830: 0x00000b54 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x4207018c 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
40824850: 0x0000002d 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x420701ac 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5
40824870: 0x00000000 0x403d0000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5



ELF file SHA256: 5542d8f16
```

### Other Steps to Reproduce

Removing from `esp_zb_task(void *pvParameters)` in ZigbeeCore.cpp the workaround device will join and report values after power off/on (without described delay device will reboot before stable work 2-3 times...) :

```
static void esp_zb_task(void *pvParameters) {
  /* initialize Zigbee stack */
  ESP_ERROR_CHECK(esp_zb_start(false));

  //NOTE: This is a workaround to make battery powered devices to be discovered as battery powered
  if (((zigbee_role_t)Zigbee.getRole() == ZIGBEE_END_DEVICE) && edBatteryPowered) {
   // zb_set_ed_node_descriptor(0, 0, 0);    <<<=====
  }

  esp_zb_stack_main_loop();
}
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

### PR DESCRIPTION
**Pull request by P-R-O-C-H-Y**
## Description of Change
TBD

## Tests scenarios
TBD

## Related links
Closes #10612

### CODE REVIEW

File: libraries/Zigbee/src/ZigbeeCore.h [hunk 1]
```diff
@@ -112,12 +113,17 @@ class ZigbeeCore {
   void setHostConfig(esp_zb_host_config_t config);
   esp_zb_host_config_t getHostConfig();
 
+  void setPrimaryChannelMask(uint32_t mask);
```
Comment (me-no-dev) [inline libraries/Zigbee/src/ZigbeeCore.h:116]: twice?

Comment (P-R-O-C-H-Y) [reply libraries/Zigbee/src/ZigbeeCore.h]: fixed, happened in conflicts resolving.

File: libraries/Zigbee/src/ZigbeeCore.cpp [hunk 2]
```diff
@@ -98,7 +99,7 @@ static void esp_zb_task(void *pvParameters) {
 
   //NOTE: This is a workaround to make battery powered devices to be discovered as battery powered
   if (((zigbee_role_t)Zigbee.getRole() == ZIGBEE_END_DEVICE) && edBatteryPowered) {
-    zb_set_ed_node_descriptor(0, 0, 0);
+    zb_set_ed_node_descriptor(0, _rx_on_when_idle, 1);
```
Comment (me-no-dev) [inline libraries/Zigbee/src/ZigbeeCore.cpp:102]: function is not a class method, so it does not have access to ` _rx_on_when_idle`. You can add a getter to the class and use `Zigbee.getRxOnWhenIdle()` instead

Comment (me-no-dev) [reply libraries/Zigbee/src/ZigbeeCore.cpp:102]: Since only one Zigbee exists, another option is to make `_rx_on_when_idle` global `static bool` for the file

File: libraries/Zigbee/src/ZigbeeCore.h [hunk 3]
```diff
@@ -118,6 +119,10 @@ class ZigbeeCore {
     return _scan_duration;
   }
 
+  void setRxOnWhenIdle(bool rx_on_when_idle) {
```
Comment (me-no-dev) [inline libraries/Zigbee/src/ZigbeeCore.h:122]: If you go with global `_rx_on_when_idle`, you would also need to implement this in the source file

**Review by lucasssvaz — APPROVED** [review]

File: libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino [hunk 4]
```diff
@@ -145,6 +142,6 @@ void loop() {
   static uint32_t last_print = 0;
   if (millis() - last_print > 30000) {
     last_print = millis();
-    zbSwitch.printBoundDevices(Serial);
+    zbSwitch.printBoundDevices();
```
Comment (me-no-dev) [inline libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino:145]: Is this change correct? Shouldn't it have Serial as argument?

Comment (P-R-O-C-H-Y) [reply libraries/Zigbee/examples/Zigbee_Color_Dimmer_Switch/Zigbee_Color_Dimmer_Switch.ino]: Yes it should, without it will print to log_i instead. Fixed, idk how that was removed.

**Review by me-no-dev — APPROVED** [review]
